POST {{baseURLAPI}}organizations/80087670016/citizens/GNVMGR75H58F335R/paymenttypes/CC00/debtpositions
Authorization: Basic {{epayapi1}} {{pass}}
Accept: application/json
Content-Type: application/json

{
  "note": "note",
  "importo": 1.0,
  "nome": "Nome",
  "cognome": "Cognome",
  "ragioneSociale": "ragione sociale",
  "email": "prova.prova@libero.it"
}
