### CDU#1 list debt positions

GET {{baseURLAPI}}organizations/{{cf_pinarolo}}/citizens/{{cf_galileo}}/debtpositions?currentPage=1&elements=10
Authorization: Basic {{user}} {{pass}}
Accept: application/json

### CDU#2

POST {{baseURLAPI}}organizations/{{cf_novara}}/citizens/{{cf_galileo}}/paymenttypes/{{tipo_pag_spontaneo}}/debtpositions
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json

{
  "note": "note",
  "importo": 3.0,
  "nome": "Galileo",
  "cognome": "Galilei",
  "email": "prova.prova@libero.it"
}

### CDU#3

GET {{baseURLAPI}}organizations/{{cf_novara}}/citizens/{{cf_pino}}/debtpositions/{{iuv_su_novara}}/paymentnotice
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json

### CDU#4

GET {{baseURLAPI}}organizations/{{cf_pinarolo}}/citizens/{{cf_pino}}/debtpositions/{{iuv_pagato_pino}}/paymentreceipt
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json

### CDU#5 tipi pagamento

GET {{baseURLAPI}}organizations/{{cf_pinarolo}}/paymenttypes
Authorization: Basic {{user}} {{pass}}
Accept: application/json

### CDU#6 pagamento spontaneo

POST {{baseURLAPI}}organizations/{{cf_novara}}/paymenttypes/{{tipo_pag_spontaneo}}/payment
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json
Accept: application/json

{
  "note": "test",
  "codiceFiscalePartitaIVAPagatore": "PVSNTN31T15L219U",
  "nome": "pino",
  "cognome": "test",
  "importo": 5.0,
  "email": "pino@test.it"
}

### CDU#7 pagamaneto posizione debitoria

GET {{baseURLAPI}}organizations/{{ofsRegionePiemonte}}/debtpositions/20231171808848270/payment
Authorization: Basic {{user}} {{pass}}
Accept: application/json

### CDU#8

PUT {{baseURLAPI}}organizations/{{cf_novara}}/citizens/{{cf_galileo}}?enableReceiptStorage=true
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json

{
}

### CDU#9

GET {{baseURLAPI}}organizations/{{cf_novara}}/citizens/{{cf_galileo}}
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json
