/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaymodric.util.wsdl.epayriconciliazioneversamentipsp;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2018-10-25T09:57:42.241+02:00
 * Generated source version: 2.4.6
 *
 */
@WebServiceClient(name = "EPayRiconciliazioneVersamentiPSP",
wsdlLocation = "/EPayRiconciliazioneVersamentiPSP.wsdl",
targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp")
public class EPayRiconciliazioneVersamentiPSP_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp", "EPayRiconciliazioneVersamentiPSP");
    public final static QName EPayRiconciliazioneVersamentiPSPSOAP = new QName("http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp", "EPayRiconciliazioneVersamentiPSPSOAP");
    static {
        URL url = null;
        try {

            url = EPayRiconciliazioneVersamentiPSP_Service.class.getResource ( "/WEB-INF/classes/EPayRiconciliazioneVersamentiPSP.wsdl" );
        } catch ( Exception e ) {
			Logger log = LogManager.getLogger ( EPayRiconciliazioneVersamentiPSP_Service.class.getName () );
            log.info (  "Can not initialize the default wsdl from EPayRiconciliazioneVersamentiPSP" );
        }
        WSDL_LOCATION = url;
    }

    public EPayRiconciliazioneVersamentiPSP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EPayRiconciliazioneVersamentiPSP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EPayRiconciliazioneVersamentiPSP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EPayRiconciliazioneVersamentiPSP_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EPayRiconciliazioneVersamentiPSP_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EPayRiconciliazioneVersamentiPSP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EPayRiconciliazioneVersamentiPSP
     */
    @WebEndpoint(name = "EPayRiconciliazioneVersamentiPSPSOAP")
    public EPayRiconciliazioneVersamentiPSP getEPayRiconciliazioneVersamentiPSPSOAP() {
        return super.getPort(EPayRiconciliazioneVersamentiPSPSOAP, EPayRiconciliazioneVersamentiPSP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EPayRiconciliazioneVersamentiPSP
     */
    @WebEndpoint(name = "EPayRiconciliazioneVersamentiPSPSOAP")
    public EPayRiconciliazioneVersamentiPSP getEPayRiconciliazioneVersamentiPSPSOAP(WebServiceFeature... features) {
        return super.getPort(EPayRiconciliazioneVersamentiPSPSOAP, EPayRiconciliazioneVersamentiPSP.class, features);
    }

}
