/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdp.mdppagopaapi.util.clientws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Feb 18 11:58:24 CET 2022
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "ChiediDatiPagamentoException", targetNamespace = "http://serviziofruitore.interfacews.mdp.nodospc.csi.it/")
public class ChiediDatiPagamentoException_Exception extends Exception {
    public static final long serialVersionUID = 20220218115824L;
    
    private it.csi.mdp.mdppagopaapi.util.clientws.ChiediDatiPagamentoException chiediDatiPagamentoException;

    public ChiediDatiPagamentoException_Exception() {
        super();
    }
    
    public ChiediDatiPagamentoException_Exception(String message) {
        super(message);
    }
    
    public ChiediDatiPagamentoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ChiediDatiPagamentoException_Exception(String message, it.csi.mdp.mdppagopaapi.util.clientws.ChiediDatiPagamentoException chiediDatiPagamentoException) {
        super(message);
        this.chiediDatiPagamentoException = chiediDatiPagamentoException;
    }

    public ChiediDatiPagamentoException_Exception(String message, it.csi.mdp.mdppagopaapi.util.clientws.ChiediDatiPagamentoException chiediDatiPagamentoException, Throwable cause) {
        super(message, cause);
        this.chiediDatiPagamentoException = chiediDatiPagamentoException;
    }

    public it.csi.mdp.mdppagopaapi.util.clientws.ChiediDatiPagamentoException getFaultInfo() {
        return this.chiediDatiPagamentoException;
    }
}
