/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdp.mdppagopaapi.util.clientws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Feb 18 11:58:24 CET 2022
 * Generated source version: 2.2.5
 *
 */


@WebServiceClient ( name = "EpayMdpWs",
wsdlLocation = "file:/C:/Users/abora/AppData/Local/Temp/tempdir36815800735362214.tmp/mdpfruitore%20(1)_1.wsdl",
targetNamespace = "http://serviziofruitore.interfacews.mdp.nodospc.csi.it/")
public class Serviziofruitoremdp_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName ( "http://serviziofruitore.interfacews.mdp.nodospc.csi.it/", "EpayMdpWs" );

    public final static QName EpayMdpWs = new QName ( "http://serviziofruitore.interfacews.mdp.nodospc.csi.it/", "EpayMdpWsPort" );
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/abora/AppData/Local/Temp/tempdir36815800735362214.tmp/mdpfruitore%20(1)_1.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/Users/abora/AppData/Local/Temp/tempdir36815800735362214.tmp/mdpfruitore%20(1)_1.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Serviziofruitoremdp_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Serviziofruitoremdp_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Serviziofruitoremdp_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return returns EpayMdpWs
     */
    @WebEndpoint ( name = "EpayMdpWsPort" )
    public Serviziofruitoremdp getServiziofruitoremdp() {
        return super.getPort ( EpayMdpWs, Serviziofruitoremdp.class );
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter
     *            will have their default values.
     * @return returns EpayMdpWs
     */
    @WebEndpoint ( name = "EpayMdpWsPort" )
    public Serviziofruitoremdp getServiziofruitoremdp(WebServiceFeature... features) {
        return super.getPort ( EpayMdpWs, Serviziofruitoremdp.class, features );
    }

}
