#GET http://tst-srv-pay-fe.bilancio.csi.it/epayfe/api/v1/organizations/80087670016/citizens/RTNLSN67E69L219X/debtpositions/24231521825177686/paymentreceipt
GET localhost:8080/epayfe/api/v1/organizations/80087670016/citizens/RTNLSN67E69L219X/debtpositions/24231521825177686/paymentreceipt
Connection: keep-alive
Content-Type: application/json
Authorization: Basic epayapi1 mypass
Host: tst-srv-oay-fe.bilancio.csi.it
User-Agent: Apache-HttpClient/4.5.10 (Java/1.8.0_291)

###

#POST http://tst-srv-pay-fe.bilancio.csi.it/epayfe/api/v1/organizations/00000000001/paymenttypes/AS10/payment
POST localhost:8080/epayfe/api/v1/organizations/00000000001/paymenttypes/AS10/payment
Connection: keep-alive
Content-Type: application/json
Authorization: Basic epayapi1 mypass
Host: tst-srv-oay-fe.bilancio.csi.it
User-Agent: Apache-HttpClient/4.5.10 (Java/1.8.0_291)

{
  "note": "test di carico",
  "importo": 191,
  "nome": "Alessandra",
  "cognome": "Osorio",
  "ragioneSociale": "",
  "codiceFiscalePartitaIVAPagatore": "00304260409",
  "email": "alessandra.osorio@consulenti.csi.it"
}

###

#PUT http://tst-srv-pay-fe.bilancio.csi.it/epayfe/api/v1/organizations/00125680033/citizens/00304260409/payment?enableReceiptStorage=true
PUT localhost:8080/epayfe/api/v1/organizations/00125680033/citizens/00304260409?enableReceiptStorage=true
Connection: keep-alive
Content-Type: application/json
Authorization: Basic epayapi1 mypass
Host: tst-srv-oay-fe.bilancio.csi.it
User-Agent: Apache-HttpClient/4.5.10 (Java/1.8.0_291)
