POST {{baseURLAPI}}organizations/{{ofsRegionePiemonte}}/paymenttypes/{{pt_spontaneo}}/payment
Authorization: Basic {{epayapi1}} {{pass}}
Content-Type: application/json
Accept: application/json

{
  "note": "pagate amme, test#{{$dynamicVariables}}",
  "codiceFiscalePartitaIVAPagatore": "clesmn87h02g388g78921234567890123456789",
  "nome": "simone",
  "cognome": "celia",
  "ragioneSociale": "simone celia",
  "importo": 1000,
  "email": "simone.celia@simonecelia.it"
}

###