/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.epay.epaypacatalogsrv.business.enums;

/**
 *
 */

public enum ParametriConfigurazione {

    SPRING_PROFILES_ACTIVE,
    MIGRATION_ENABLE,
    WSO2_LOGGING_PAYLOAD,
    WSO2_CONNECTION_TIMEOUT,
    WSO2_RECEIVE_TIMEOUT,
    NUM_MAX_THREAD,
    WSO2_ENABLE,
    MAIL_ACTIVE,
    DEFAULT_EMAIL_ADDRESS,
    DEFAULT_EMAIL_ASSISTENZA_ADDRESS,
    MAIL_TRANSPORT_PROTOCOL,
    MAIL_SMTP_AUTH,
    MAIL_SMTP_STARTTLS_ENABLE,
    SMTP_SERVER,
    SMTP_USER,
    SMTP_PASSWORD,
    SMTP_SENDER,
    SMTP_EMERGENCY,
    SMTP_PORT,
    SMTP_RETRYDELAY,
    SMTP_RETRY,
    RICHIEDI_APPLICATION_ID_ENDPOINT,
    JOB_ALERT_SCADENZA_RIF_CONTAB_RANGE_GIORNI,
    CONFIG_MAX_NUM_CAR_DESC_COV_INVIO_NOTIFY
}
