/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdpcore;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMdpCoreCxf", targetNamespace = "http://interfacecxf.core.mdp.csi.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMdpCoreCxf {


    /**
     * 
     * @param applicationId
     * @param transactionId
     * @return
     *     returns it.csi.mdpcore.InformativePSPScelto
     * @throws NamingException_Exception
     * @throws CreateException_Exception
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSceltaWisp", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetSceltaWisp")
    @ResponseWrapper(localName = "getSceltaWispResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetSceltaWispResponse")
    public InformativePSPScelto getSceltaWisp(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "transactionId", targetNamespace = "")
        String transactionId)
        throws CSIException_Exception, CreateException_Exception, DaoException_Exception, MissingParameterException_Exception, NamingException_Exception
    ;

    /**
     * 
     * @param transactionId
     * @return
     *     returns it.csi.mdpcore.Transazione
     * @throws NamingException_Exception
     * @throws CreateException_Exception
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatoTransazione", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetStatoTransazione")
    @ResponseWrapper(localName = "getStatoTransazioneResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetStatoTransazioneResponse")
    public Transazione getStatoTransazione(
        @WebParam(name = "transaction_id", targetNamespace = "")
        String transactionId)
        throws CSIException_Exception, CreateException_Exception, DaoException_Exception, MissingParameterException_Exception, NamingException_Exception
    ;

    /**
     * 
     * @param applicationId
     * @param gatewayId
     * @return
     *     returns it.csi.mdpcore.Vapplicationcomuni
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPagonetCustomData", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetPagonetCustomData")
    @ResponseWrapper(localName = "getPagonetCustomDataResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetPagonetCustomDataResponse")
    public Vapplicationcomuni getPagonetCustomData(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "gatewayId", targetNamespace = "")
        String gatewayId)
        throws CSIException_Exception, DaoException_Exception, MissingParameterException_Exception
    ;

    /**
     * 
     * @param basketId
     * @param appId
     * @return
     *     returns it.csi.mdpcore.Transazione
     * @throws CreateException_Exception
     * @throws NamingException_Exception
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws SOAPFaultException_Exception
     * @throws DatatypeConfigurationException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "initTransazione", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.InitTransazione")
    @ResponseWrapper(localName = "initTransazioneResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.InitTransazioneResponse")
    public Transazione initTransazione(
        @WebParam(name = "appId", targetNamespace = "")
        String appId,
        @WebParam(name = "basketId", targetNamespace = "")
        String basketId)
        throws CSIException_Exception, CreateException_Exception, DaoException_Exception, DatatypeConfigurationException_Exception, MissingParameterException_Exception, NamingException_Exception, SOAPFaultException_Exception
    ;

    /**
     * 
     * @param iuv
     * @param transactionId
     * @return
     *     returns it.csi.mdpcore.RicevutaTelematicaNodo
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRTperIUVTransazione", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetRTperIUVTransazione")
    @ResponseWrapper(localName = "getRTperIUVTransazioneResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetRTperIUVTransazioneResponse")
    public RicevutaTelematicaNodo getRTperIUVTransazione(
        @WebParam(name = "iuv", targetNamespace = "")
        String iuv,
        @WebParam(name = "transactionId", targetNamespace = "")
        String transactionId)
        throws CSIException_Exception, DaoException_Exception, MissingParameterException_Exception
    ;

    /**
     * 
     * @param appId
     * @return
     *     returns it.csi.mdpcore.Application
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplication", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetApplication")
    @ResponseWrapper(localName = "getApplicationResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetApplicationResponse")
    public Application getApplication(
        @WebParam(name = "appId", targetNamespace = "")
        String appId)
        throws CSIException_Exception, DaoException_Exception, MissingParameterException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.mdpcore.PartAnComune
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComuneProvincia", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetComuneProvincia")
    @ResponseWrapper(localName = "getComuneProvinciaResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetComuneProvinciaResponse")
    public PartAnComune getComuneProvincia(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CSIException_Exception, DaoException_Exception, MissingParameterException_Exception
    ;

    /**
     * 
     * @param t
     * @param appId
     * @return
     *     returns java.util.List<it.csi.mdpcore.AppGateway>
     * @throws NamingException_Exception
     * @throws CreateException_Exception
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getModalitaPagamento", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetModalitaPagamento")
    @ResponseWrapper(localName = "getModalitaPagamentoResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetModalitaPagamentoResponse")
    public List<AppGateway> getModalitaPagamento(
        @WebParam(name = "t", targetNamespace = "")
        Transazione t,
        @WebParam(name = "appId", targetNamespace = "")
        String appId)
        throws CSIException_Exception, CreateException_Exception, DaoException_Exception, MissingParameterException_Exception, NamingException_Exception
    ;

    /**
     * 
     * @param iuv
     * @return
     *     returns java.util.List<it.csi.mdpcore.RicevutaTelematicaNodo>
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaRTperIUV", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetListaRTperIUV")
    @ResponseWrapper(localName = "getListaRTperIUVResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetListaRTperIUVResponse")
    public List<RicevutaTelematicaNodo> getListaRTperIUV(
        @WebParam(name = "iuv", targetNamespace = "")
        String iuv)
        throws CSIException_Exception, DaoException_Exception, MissingParameterException_Exception
    ;

    /**
     * 
     * @param applicationId
     * @param transactionId
     * @return
     *     returns java.util.List<it.csi.mdpcore.NodoErrore>
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getErroriNodo", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetErroriNodo")
    @ResponseWrapper(localName = "getErroriNodoResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetErroriNodoResponse")
    public List<NodoErrore> getErroriNodo(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "transactionId", targetNamespace = "")
        String transactionId)
        throws CSIException_Exception, DaoException_Exception, MissingParameterException_Exception
    ;

    /**
     * 
     * @param parametriUrlWisp
     * @param applicationId
     * @param parametriAggiuntivi
     * @param transazione
     * @return
     *     returns java.lang.String
     * @throws NamingException_Exception
     * @throws CreateException_Exception
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUrlWisp", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetUrlWisp")
    @ResponseWrapper(localName = "getUrlWispResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetUrlWispResponse")
    public String getUrlWisp(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "transazione", targetNamespace = "")
        Transazione transazione,
        @WebParam(name = "parametriUrlWisp", targetNamespace = "")
        ParametriUrlWisp parametriUrlWisp,
        @WebParam(name = "parametriAggiuntivi", targetNamespace = "")
        List<ChiaveValore> parametriAggiuntivi)
        throws CSIException_Exception, CreateException_Exception, DaoException_Exception, MissingParameterException_Exception, NamingException_Exception
    ;

    /**
     * 
     * @param t
     * @param appId
     * @return
     *     returns java.util.List<it.csi.mdpcore.AppGatewayInformativa>
     * @throws NamingException_Exception
     * @throws CreateException_Exception
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getModalitaInformativePagamento", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetModalitaInformativePagamento")
    @ResponseWrapper(localName = "getModalitaInformativePagamentoResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetModalitaInformativePagamentoResponse")
    public List<AppGatewayInformativa> getModalitaInformativePagamento(
        @WebParam(name = "t", targetNamespace = "")
        Transazione t,
        @WebParam(name = "appId", targetNamespace = "")
        String appId)
        throws CSIException_Exception, CreateException_Exception, DaoException_Exception, MissingParameterException_Exception, NamingException_Exception
    ;

    /**
     * 
     * @param tea
     * @param t
     * @return
     *     returns java.lang.String
     * @throws NamingException_Exception
     * @throws CreateException_Exception
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startTransazione", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.StartTransazione")
    @ResponseWrapper(localName = "startTransazioneResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.StartTransazioneResponse")
    public String startTransazione(
        @WebParam(name = "t", targetNamespace = "")
        Transazione t,
        @WebParam(name = "tea", targetNamespace = "")
        List<TransazioneExtraAttribute> tea)
        throws CSIException_Exception, CreateException_Exception, DaoException_Exception, MissingParameterException_Exception, NamingException_Exception
    ;

    /**
     * 
     * @param iuv
     * @return
     *     returns it.csi.mdpcore.RicevutaTelematicaNodo
     * @throws DaoException_Exception
     * @throws CSIException_Exception
     * @throws MissingParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRTperIUV", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetRTperIUV")
    @ResponseWrapper(localName = "getRTperIUVResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.GetRTperIUVResponse")
    public RicevutaTelematicaNodo getRTperIUV(
        @WebParam(name = "iuv", targetNamespace = "")
        String iuv)
        throws CSIException_Exception, DaoException_Exception, MissingParameterException_Exception
    ;

    /**
     * 
     * @param tea
     * @param t
     * @param elencoRPT
     * @return
     *     returns java.lang.String
     * @throws BusinessException_Exception
     * @throws SystemException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startTransazioneCarrello", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.StartTransazioneCarrello")
    @ResponseWrapper(localName = "startTransazioneCarrelloResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdpcore.StartTransazioneCarrelloResponse")
    public String startTransazioneCarrello(
        @WebParam(name = "t", targetNamespace = "")
        Transazione t,
        @WebParam(name = "tea", targetNamespace = "")
        List<TransazioneExtraAttribute> tea,
        @WebParam(name = "elencoRPT", targetNamespace = "")
        ElencoRPT elencoRPT,
        @WebParam(name = "multiBeneficiario", targetNamespace = "")
        Boolean multiBeneficiario)
        throws BusinessException_Exception, SystemException_Exception
    ;

}
