/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Jan 10 16:03:31 CET 2022
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", name = "Epaypacatalogsrv")
@XmlSeeAlso({ObjectFactory.class})
public interface Epaypacatalogsrv {

    @WebMethod
    @RequestWrapper(localName = "elaboraCodaEmail", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.ElaboraCodaEmail")
    @ResponseWrapper(localName = "elaboraCodaEmailResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.ElaboraCodaEmailResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.ElaboraCodaEmailOutput elaboraCodaEmail(
        @WebParam(name = "elaboraCodaEmailInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.ElaboraCodaEmailInput elaboraCodaEmailInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProfilazioneUtenteCorrente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetProfilazioneUtenteCorrente")
    @ResponseWrapper(localName = "getProfilazioneUtenteCorrenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetProfilazioneUtenteCorrenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetProfilazioneUtenteCorrenteOutput getProfilazioneUtenteCorrente(
        @WebParam(name = "getProfilazioneUtenteCorrenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetProfilazioneUtenteCorrenteInput getProfilazioneUtenteCorrenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniPeriodicitaSchedulazioneRiconciliazione", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniPeriodicitaSchedulazioneRiconciliazione")
    @ResponseWrapper(localName = "getOpzioniPeriodicitaSchedulazioneRiconciliazioneResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniPeriodicitaSchedulazioneRiconciliazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniPeriodicitaSchedulazioneRiconciliazioneOutput getOpzioniPeriodicitaSchedulazioneRiconciliazione(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetUtente")
    @ResponseWrapper(localName = "getUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetUtenteOutput getUtente(
        @WebParam(name = "getUtenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetUtenteInput getUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaUtente")
    @ResponseWrapper(localName = "ricercaUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaUtenteOutput ricercaUtente(
        @WebParam(name = "ricercaUtenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaUtenteInput ricercaUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessaggi", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetMessaggi")
    @ResponseWrapper(localName = "getMessaggiResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetMessaggiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetMessaggiOutput getMessaggi(
        @WebParam(name = "getMessaggiInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetMessaggiInput getMessaggiInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaRiferimentoContabile")
    @ResponseWrapper(localName = "ricercaRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaRiferimentoContabileOutput ricercaRiferimentoContabile(
        @WebParam(name = "ricercaRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaRiferimentoContabileInput ricercaRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "autorizzaEsportazioneDati", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AutorizzaEsportazioneDati")
    @ResponseWrapper(localName = "autorizzaEsportazioneDatiResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AutorizzaEsportazioneDatiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AutorizzaEsportazioneDatiOutput autorizzaEsportazioneDati(
        @WebParam(name = "autorizzaEsportazioneDatiInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AutorizzaEsportazioneDatiInput autorizzaEsportazioneDatiInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTematica", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTematica")
    @ResponseWrapper(localName = "getOpzioniTematicaResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTematicaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTematicaOutput getOpzioniTematica(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniAssociazioneUtenteCdu", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniAssociazioneUtenteCdu")
    @ResponseWrapper(localName = "getOpzioniAssociazioneUtenteCduResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniAssociazioneUtenteCduResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniAssociazioneUtenteCduOutput getOpzioniAssociazioneUtenteCdu(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetRiferimentoContabile")
    @ResponseWrapper(localName = "getRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "") it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetRiferimentoContabileOutput getRiferimentoContabile(
        @WebParam(name = "getRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetRiferimentoContabileInput getRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEnte", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEnte")
    @ResponseWrapper(localName = "getEnteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEnteResponse")
    @WebResult(name = "result", targetNamespace = "") it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEnteOutput getEnte(
        @WebParam(name = "getEnteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEnteInput getEnteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniAssociazioneUtenteTematica", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniAssociazioneUtenteTematica")
    @ResponseWrapper(localName = "getOpzioniAssociazioneUtenteTematicaResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniAssociazioneUtenteTematicaResponse")
    @WebResult(name = "result", targetNamespace = "") it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniAssociazioneUtenteTematicaOutput getOpzioniAssociazioneUtenteTematica(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetCodiceVersamento")
    @ResponseWrapper(localName = "getCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "") it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetCodiceVersamentoOutput getCodiceVersamento(
        @WebParam(name = "getCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetCodiceVersamentoInput getCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTipologiaDatoSpecificoRiscossione", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipologiaDatoSpecificoRiscossione")
    @ResponseWrapper(localName = "getOpzioniTipologiaDatoSpecificoRiscossioneResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipologiaDatoSpecificoRiscossioneResponse")
    @WebResult(name = "result", targetNamespace = "") it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipologiaDatoSpecificoRiscossioneOutput getOpzioniTipologiaDatoSpecificoRiscossione(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaRiferimentiContabiliSecondariPerCov", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaRiferimentiContabiliSecondariPerCov")
    @ResponseWrapper(localName = "ricercaRiferimentiContabiliSecondariPerCovResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaRiferimentiContabiliSecondariPerCovResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaRiferimentiContabiliSecondariPerCovOutput ricercaRiferimentiContabiliSecondariPerCov(
        @WebParam(name = "ricercaRiferimentiContabiliSecondariPerCovInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaRiferimentiContabiliSecondariPerCovInput ricercaRiferimentiContabiliSecondariPerCovInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciCodiceVersamento")
    @ResponseWrapper(localName = "inserisciCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciCodiceVersamentoOutput inserisciCodiceVersamento(
        @WebParam(name = "inserisciCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciCodiceVersamentoInput inserisciCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eliminaUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaUtente")
    @ResponseWrapper(localName = "eliminaUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaUtenteOutput eliminaUtente(
        @WebParam(name = "eliminaUtenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaUtenteInput eliminaUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProfilazioneUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetProfilazioneUtente")
    @ResponseWrapper(localName = "getProfilazioneUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetProfilazioneUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetProfilazioneUtenteOutput getProfilazioneUtente(
        @WebParam(name = "getProfilazioneUtenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetProfilazioneUtenteInput getProfilazioneUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eseguiMigrazione", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EseguiMigrazione")
    @ResponseWrapper(localName = "eseguiMigrazioneResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EseguiMigrazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EseguiMigrazioneOutput eseguiMigrazione(
        @WebParam(name = "eseguiMigrazioneInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EseguiMigrazioneInput eseguiMigrazioneInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaCodiceVersamentoRifContabileSecondario", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaCodiceVersamentoRifContabileSecondario")
    @ResponseWrapper(localName = "ricercaCodiceVersamentoRifContabileSecondarioResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaCodiceVersamentoRifContabileSecondarioResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaCodiceVersamentoRifContabileSecondarioOutput ricercaCodiceVersamentoRifContabileSecondario(
        @WebParam(name = "ricercaCodiceVersamentoRifContabileSecondarioInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaCodiceVersamentoRifContabileSecondarioInput ricercaCodiceVersamentoRifContabileSecondarioInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniStatoAggiornamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniStatoAggiornamento")
    @ResponseWrapper(localName = "getOpzioniStatoAggiornamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniStatoAggiornamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniStatoAggiornamentoOutput getOpzioniStatoAggiornamento(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    );

    @WebMethod
    @RequestWrapper(localName = "ricercaVoceEntrata", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaVoceEntrata")
    @ResponseWrapper(localName = "ricercaVoceEntrataResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaVoceEntrataResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaVoceEntrataOutput ricercaVoceEntrata(
        @WebParam(name = "ricercaVoceEntrataInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaVoceEntrataInput ricercaVoceEntrataInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaRiferimentoContabile")
    @ResponseWrapper(localName = "aggiornaRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaRiferimentoContabileOutput aggiornaRiferimentoContabile(
        @WebParam(name = "aggiornaRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaRiferimentoContabileInput aggiornaRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEntiConRiferimentoContabileSecondario", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEntiConRiferimentoContabileSecondario")
    @ResponseWrapper(localName = "getEntiConRiferimentoContabileSecondarioResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEntiConRiferimentoContabileSecondarioResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEntiConRiferimentoContabileSecondarioOutput getEntiConRiferimentoContabileSecondario(
        @WebParam(name = "getEntiConRiferimentoContabileSecondarioInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEntiConRiferimentoContabileSecondarioInput getEntiConRiferimentoContabileSecondarioInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniStatoAggiornamentoEnte", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniStatoAggiornamentoEnte")
    @ResponseWrapper(localName = "getOpzioniStatoAggiornamentoEnteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniStatoAggiornamentoEnteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniStatoAggiornamentoEnteOutput getOpzioniStatoAggiornamentoEnte(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "chiudiRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.ChiudiRiferimentoContabile")
    @ResponseWrapper(localName = "chiudiRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.ChiudiRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.ChiudiRiferimentoContabileOutput chiudiRiferimentoContabile(
        @WebParam(name = "chiudiRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.ChiudiRiferimentoContabileInput chiudiRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaCodiceVersamento")
    @ResponseWrapper(localName = "ricercaCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaCodiceVersamentoOutput ricercaCodiceVersamento(
        @WebParam(name = "ricercaCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaCodiceVersamentoInput ricercaCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaVoceEntrataDisponibile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaVoceEntrataDisponibile")
    @ResponseWrapper(localName = "ricercaVoceEntrataDisponibileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaVoceEntrataDisponibileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaVoceEntrataDisponibileOutput ricercaVoceEntrataDisponibile(
        @WebParam(name = "ricercaVoceEntrataDisponibileInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.RicercaVoceEntrataDisponibileInput ricercaVoceEntrataDisponibileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaTematicheUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaTematicheUtente")
    @ResponseWrapper(localName = "aggiornaTematicheUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaTematicheUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaTematicheUtenteOutput aggiornaTematicheUtente(
        @WebParam(name = "aggiornaTematicheUtenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaTematicheUtenteInput aggiornaTematicheUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniModalitaAcquisizioneProvvisori", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniModalitaAcquisizioneProvvisori")
    @ResponseWrapper(localName = "getOpzioniModalitaAcquisizioneProvvisoriResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniModalitaAcquisizioneProvvisoriResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniModalitaAcquisizioneProvvisoriOutput getOpzioniModalitaAcquisizioneProvvisori(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaEnte", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaEnte")
    @ResponseWrapper(localName = "aggiornaEnteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaEnteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaEnteOutput aggiornaEnte(
        @WebParam(name = "modificaEnteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaEnteInput modificaEnteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciRiferimentoContabile")
    @ResponseWrapper(localName = "inserisciRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "") it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciRiferimentoContabileOutput inserisciRiferimentoContabile(
        @WebParam(name = "inserisciRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciRiferimentoContabileInput inserisciRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciUtente")
    @ResponseWrapper(localName = "inserisciUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciUtenteOutput inserisciUtente(
        @WebParam(name = "inserisciUtenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.InserisciUtenteInput inserisciUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaCodiceVersamento")
    @ResponseWrapper(localName = "aggiornaCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaCodiceVersamentoOutput aggiornaCodiceVersamento(
        @WebParam(name = "aggiornaCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaCodiceVersamentoInput aggiornaCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTipoPagamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipoPagamento")
    @ResponseWrapper(localName = "getOpzioniTipoPagamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipoPagamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipoPagamentoOutput getOpzioniTipoPagamento(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaCduUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaCduUtente")
    @ResponseWrapper(localName = "aggiornaCduUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaCduUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaCduUtenteOutput aggiornaCduUtente(
        @WebParam(name = "aggiornaCduUtenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaCduUtenteInput aggiornaCduUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eliminaRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaRiferimentoContabile")
    @ResponseWrapper(localName = "eliminaRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaRiferimentoContabileOutput eliminaRiferimentoContabile(
        @WebParam(name = "eliminaRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaRiferimentoContabileInput eliminaRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "testResources", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.TestResources")
    @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.TestResourcesResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.TestResourcesOutput testResources(
        @WebParam(name = "testResourcesInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.TestResourcesInput testResourcesInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eliminaCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaCodiceVersamento")
    @ResponseWrapper(localName = "eliminaCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaCodiceVersamentoOutput eliminaCodiceVersamento(
        @WebParam(name = "eliminaCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EliminaCodiceVersamentoInput eliminaCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniModalitaIntegrazione", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniModalitaIntegrazione")
    @ResponseWrapper(localName = "getOpzioniModalitaIntegrazioneResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniModalitaIntegrazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniModalitaIntegrazioneOutput getOpzioniModalitaIntegrazione(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEntiAssociati", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEntiAssociati")
    @ResponseWrapper(localName = "getEntiAssociatiResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEntiAssociatiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEntiAssociatiOutput getEntiAssociati(
        @WebParam(name = "getEntiAssociatiInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetEntiAssociatiInput getEntiAssociatiInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTematicaClean", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTematicaClean")
    @ResponseWrapper(localName = "getOpzioniTematicaCleanResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTematicaCleanResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTematicaCleanOutput getOpzioniTematicaClean(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniCodiceVersamento")
    @ResponseWrapper(localName = "getOpzioniCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniCodiceVersamentoOutput getOpzioniCodiceVersamento(
        @WebParam(name = "getOpzioniCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniCodiceVersamentoInput getOpzioniCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniMacrotipo", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniMacrotipo")
    @ResponseWrapper(localName = "getOpzioniMacrotipoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniMacrotipoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniMacrotipoOutput getOpzioniMacrotipo(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaUtente")
    @ResponseWrapper(localName = "aggiornaUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaUtenteOutput aggiornaUtente(
        @WebParam(name = "aggiornaUtenteInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.AggiornaUtenteInput aggiornaUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTipologiaAccertamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipologiaAccertamento")
    @ResponseWrapper(localName = "getOpzioniTipologiaAccertamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipologiaAccertamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniTipologiaAccertamentoOutput getOpzioniTipologiaAccertamento(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;
}
