/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-06-10T14:12:29.633+02:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "EpaypacatalogsrvException", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/")
public class EpaypacatalogsrvException_Exception extends java.lang.Exception {

    private it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EpaypacatalogsrvException epaypacatalogsrvException;

    public EpaypacatalogsrvException_Exception() {
        super();
    }

    public EpaypacatalogsrvException_Exception(String message) {
        super(message);
    }

    public EpaypacatalogsrvException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EpaypacatalogsrvException_Exception(String message, it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EpaypacatalogsrvException epaypacatalogsrvException) {
        super(message);
        this.epaypacatalogsrvException = epaypacatalogsrvException;
    }

    public EpaypacatalogsrvException_Exception(String message, it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EpaypacatalogsrvException epaypacatalogsrvException, java.lang.Throwable cause) {
        super(message, cause);
        this.epaypacatalogsrvException = epaypacatalogsrvException;
    }

    public it.csi.epay.epaypacatalogweb.integration.stubs.epaypacatalogsrv.EpaypacatalogsrvException getFaultInfo() {
        return this.epaypacatalogsrvException;
    }
}
