/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epayfeapi.soap.client.mdp.core.interfacecxf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-03-15T20:45:31.056+01:00
 * Generated source version: 3.3.0
 */

@WebFault ( name = "SystemException", targetNamespace = "http://www.csi.it/mdp/" )
@SuppressWarnings ( "unused" )
public class SystemException extends Exception {

	public static final long serialVersionUID = 1L;

	private it.csi.epay.epayfeapi.soap.client.mdp.SystemException systemException;

	public SystemException () {
		super ();
	}

	public SystemException ( String message ) {
		super ( message );
	}

	public SystemException ( String message, Throwable cause ) {
		super ( message, cause );
	}

	public SystemException ( String message, it.csi.epay.epayfeapi.soap.client.mdp.SystemException systemException ) {
		super ( message );
		this.systemException = systemException;
	}

	public SystemException ( String message, it.csi.epay.epayfeapi.soap.client.mdp.SystemException systemException, Throwable cause ) {
		super ( message, cause );
		this.systemException = systemException;
	}

	public it.csi.epay.epayfeapi.soap.client.mdp.SystemException getFaultInfo () {
		return this.systemException;
	}
}
