/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdp.mdpboweb.business.ws.coreCxf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Tue Mar 13 14:35:35 CET 2012
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "CreateException", targetNamespace = "http://interfacecxf.core.mdp.csi.it/")
public class CreateException_Exception extends Exception {
    public static final long serialVersionUID = 20120313143535L;
    
    private it.csi.mdp.mdpboweb.business.ws.coreCxf.CreateException createException;

    public CreateException_Exception() {
        super();
    }
    
    public CreateException_Exception(String message) {
        super(message);
    }
    
    public CreateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CreateException_Exception(String message, it.csi.mdp.mdpboweb.business.ws.coreCxf.CreateException createException) {
        super(message);
        this.createException = createException;
    }

    public CreateException_Exception(String message, it.csi.mdp.mdpboweb.business.ws.coreCxf.CreateException createException, Throwable cause) {
        super(message, cause);
        this.createException = createException;
    }

    public it.csi.mdp.mdpboweb.business.ws.coreCxf.CreateException getFaultInfo() {
        return this.createException;
    }
}
