/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdp.mdpboweb.business.ws.coreCxf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Tue Mar 13 14:35:35 CET 2012
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "DaoException", targetNamespace = "http://interfacecxf.core.mdp.csi.it/")
public class DaoException_Exception extends Exception {
    public static final long serialVersionUID = 20120313143535L;
    
    private it.csi.mdp.mdpboweb.business.ws.coreCxf.DaoException daoException;

    public DaoException_Exception() {
        super();
    }
    
    public DaoException_Exception(String message) {
        super(message);
    }
    
    public DaoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DaoException_Exception(String message, it.csi.mdp.mdpboweb.business.ws.coreCxf.DaoException daoException) {
        super(message);
        this.daoException = daoException;
    }

    public DaoException_Exception(String message, it.csi.mdp.mdpboweb.business.ws.coreCxf.DaoException daoException, Throwable cause) {
        super(message, cause);
        this.daoException = daoException;
    }

    public it.csi.mdp.mdpboweb.business.ws.coreCxf.DaoException getFaultInfo() {
        return this.daoException;
    }
}
