/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.mdp.mdpboweb.business.ws.coreCxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Tue Mar 13 14:35:35 CET 2012
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://interfacecxf.core.mdp.csi.it/", name = "IMdpCoreCxf")
@XmlSeeAlso({ObjectFactory.class})
public interface IMdpCoreCxf {

    @ResponseWrapper(localName = "getStatoTransazioneResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetStatoTransazioneResponse")
    @RequestWrapper(localName = "getStatoTransazione", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetStatoTransazione")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public it.csi.mdp.mdpboweb.business.ws.coreCxf.Transazione getStatoTransazione(
        @WebParam(name = "transaction_id", targetNamespace = "")
        java.lang.String transactionId
    ) throws DaoException_Exception, NamingException_Exception, CreateException_Exception, MissingParameterException_Exception;

    @ResponseWrapper(localName = "getPagonetCustomDataResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetPagonetCustomDataResponse")
    @RequestWrapper(localName = "getPagonetCustomData", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetPagonetCustomData")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public it.csi.mdp.mdpboweb.business.ws.coreCxf.Vapplicationcomuni getPagonetCustomData(
        @WebParam(name = "applicationId", targetNamespace = "")
        java.lang.String applicationId,
        @WebParam(name = "gatewayId", targetNamespace = "")
        java.lang.String gatewayId
    ) throws DaoException_Exception, MissingParameterException_Exception;

    @ResponseWrapper(localName = "initTransazioneResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.InitTransazioneResponse")
    @RequestWrapper(localName = "initTransazione", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.InitTransazione")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public it.csi.mdp.mdpboweb.business.ws.coreCxf.Transazione initTransazione(
        @WebParam(name = "appId", targetNamespace = "")
        java.lang.String appId,
        @WebParam(name = "basketId", targetNamespace = "")
        java.lang.String basketId
    ) throws DatatypeConfigurationException_Exception, DaoException_Exception, NamingException_Exception, CreateException_Exception, SOAPFaultException_Exception, MissingParameterException_Exception;

    @ResponseWrapper(localName = "getApplicationResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetApplicationResponse")
    @RequestWrapper(localName = "getApplication", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetApplication")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public it.csi.mdp.mdpboweb.business.ws.coreCxf.Application getApplication(
        @WebParam(name = "appId", targetNamespace = "")
        java.lang.String appId
    ) throws DaoException_Exception, MissingParameterException_Exception;

    @ResponseWrapper(localName = "getComuneProvinciaResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetComuneProvinciaResponse")
    @RequestWrapper(localName = "getComuneProvincia", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetComuneProvincia")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public it.csi.mdp.mdpboweb.business.ws.coreCxf.PartAnComune getComuneProvincia(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws DaoException_Exception, MissingParameterException_Exception;

    @ResponseWrapper(localName = "getModalitaPagamentoResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetModalitaPagamentoResponse")
    @RequestWrapper(localName = "getModalitaPagamento", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.GetModalitaPagamento")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public java.util.List<it.csi.mdp.mdpboweb.business.ws.coreCxf.AppGateway> getModalitaPagamento(
        @WebParam(name = "t", targetNamespace = "")
        it.csi.mdp.mdpboweb.business.ws.coreCxf.Transazione t,
        @WebParam(name = "appId", targetNamespace = "")
        java.lang.String appId
    ) throws DaoException_Exception, NamingException_Exception, CreateException_Exception, MissingParameterException_Exception;

    @ResponseWrapper(localName = "startTransazioneResponse", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.StartTransazioneResponse")
    @RequestWrapper(localName = "startTransazione", targetNamespace = "http://interfacecxf.core.mdp.csi.it/", className = "it.csi.mdp.mdpboweb.business.ws.coreCxf.StartTransazione")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public java.lang.String startTransazione(
        @WebParam(name = "t", targetNamespace = "")
        it.csi.mdp.mdpboweb.business.ws.coreCxf.Transazione t,
        @WebParam(name = "tea", targetNamespace = "")
        java.util.List<it.csi.mdp.mdpboweb.business.ws.coreCxf.TransazioneExtraAttribute> tea
    ) throws DaoException_Exception, NamingException_Exception, CreateException_Exception, MissingParameterException_Exception;
}
