/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdp.mdpboweb.business.ws.coreCxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Tue Mar 13 14:35:35 CET 2012
 * Generated source version: 2.2.5
 * 
 */

public final class IMdpCoreCxf_MdpCoreCxfPort_Client {

    private static final QName SERVICE_NAME = new QName("http://interfacecxf.core.mdp.csi.it/", "MdpCoreCxfService");

    private IMdpCoreCxf_MdpCoreCxfPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MdpCoreCxfService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MdpCoreCxfService ss = new MdpCoreCxfService(wsdlURL, SERVICE_NAME);
        IMdpCoreCxf port = ss.getMdpCoreCxfPort();  
        
        {
        System.out.println("Invoking getStatoTransazione...");
        java.lang.String _getStatoTransazione_transactionId = "";
        try {
            it.csi.mdp.mdpboweb.business.ws.coreCxf.Transazione _getStatoTransazione__return = port.getStatoTransazione(_getStatoTransazione_transactionId);
            System.out.println("getStatoTransazione.result=" + _getStatoTransazione__return);

        } catch (DaoException_Exception e) { 
            System.out.println("Expected exception: DaoException has occurred.");
            System.out.println(e.toString());
        } catch (NamingException_Exception e) { 
            System.out.println("Expected exception: NamingException has occurred.");
            System.out.println(e.toString());
        } catch (CreateException_Exception e) { 
            System.out.println("Expected exception: CreateException has occurred.");
            System.out.println(e.toString());
        } catch (MissingParameterException_Exception e) { 
            System.out.println("Expected exception: MissingParameterException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPagonetCustomData...");
        java.lang.String _getPagonetCustomData_applicationId = "";
        java.lang.String _getPagonetCustomData_gatewayId = "";
        try {
            it.csi.mdp.mdpboweb.business.ws.coreCxf.Vapplicationcomuni _getPagonetCustomData__return = port.getPagonetCustomData(_getPagonetCustomData_applicationId, _getPagonetCustomData_gatewayId);
            System.out.println("getPagonetCustomData.result=" + _getPagonetCustomData__return);

        } catch (DaoException_Exception e) { 
            System.out.println("Expected exception: DaoException has occurred.");
            System.out.println(e.toString());
        } catch (MissingParameterException_Exception e) { 
            System.out.println("Expected exception: MissingParameterException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking initTransazione...");
        java.lang.String _initTransazione_appId = "";
        java.lang.String _initTransazione_basketId = "";
        try {
            it.csi.mdp.mdpboweb.business.ws.coreCxf.Transazione _initTransazione__return = port.initTransazione(_initTransazione_appId, _initTransazione_basketId);
            System.out.println("initTransazione.result=" + _initTransazione__return);

        } catch (DatatypeConfigurationException_Exception e) { 
            System.out.println("Expected exception: DatatypeConfigurationException has occurred.");
            System.out.println(e.toString());
        } catch (DaoException_Exception e) { 
            System.out.println("Expected exception: DaoException has occurred.");
            System.out.println(e.toString());
        } catch (NamingException_Exception e) { 
            System.out.println("Expected exception: NamingException has occurred.");
            System.out.println(e.toString());
        } catch (CreateException_Exception e) { 
            System.out.println("Expected exception: CreateException has occurred.");
            System.out.println(e.toString());
        } catch (SOAPFaultException_Exception e) { 
            System.out.println("Expected exception: SOAPFaultException has occurred.");
            System.out.println(e.toString());
        } catch (MissingParameterException_Exception e) { 
            System.out.println("Expected exception: MissingParameterException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getApplication...");
        java.lang.String _getApplication_appId = "";
        try {
            it.csi.mdp.mdpboweb.business.ws.coreCxf.Application _getApplication__return = port.getApplication(_getApplication_appId);
            System.out.println("getApplication.result=" + _getApplication__return);

        } catch (DaoException_Exception e) { 
            System.out.println("Expected exception: DaoException has occurred.");
            System.out.println(e.toString());
        } catch (MissingParameterException_Exception e) { 
            System.out.println("Expected exception: MissingParameterException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getComuneProvincia...");
        java.lang.String _getComuneProvincia_arg0 = "";
        try {
            it.csi.mdp.mdpboweb.business.ws.coreCxf.PartAnComune _getComuneProvincia__return = port.getComuneProvincia(_getComuneProvincia_arg0);
            System.out.println("getComuneProvincia.result=" + _getComuneProvincia__return);

        } catch (DaoException_Exception e) { 
            System.out.println("Expected exception: DaoException has occurred.");
            System.out.println(e.toString());
        } catch (MissingParameterException_Exception e) { 
            System.out.println("Expected exception: MissingParameterException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getModalitaPagamento...");
        it.csi.mdp.mdpboweb.business.ws.coreCxf.Transazione _getModalitaPagamento_t = null;
        java.lang.String _getModalitaPagamento_appId = "";
        try {
            java.util.List<it.csi.mdp.mdpboweb.business.ws.coreCxf.AppGateway> _getModalitaPagamento__return = port.getModalitaPagamento(_getModalitaPagamento_t, _getModalitaPagamento_appId);
            System.out.println("getModalitaPagamento.result=" + _getModalitaPagamento__return);

        } catch (DaoException_Exception e) { 
            System.out.println("Expected exception: DaoException has occurred.");
            System.out.println(e.toString());
        } catch (NamingException_Exception e) { 
            System.out.println("Expected exception: NamingException has occurred.");
            System.out.println(e.toString());
        } catch (CreateException_Exception e) { 
            System.out.println("Expected exception: CreateException has occurred.");
            System.out.println(e.toString());
        } catch (MissingParameterException_Exception e) { 
            System.out.println("Expected exception: MissingParameterException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking startTransazione...");
        it.csi.mdp.mdpboweb.business.ws.coreCxf.Transazione _startTransazione_t = null;
        java.util.List<it.csi.mdp.mdpboweb.business.ws.coreCxf.TransazioneExtraAttribute> _startTransazione_tea = null;
        try {
            java.lang.String _startTransazione__return = port.startTransazione(_startTransazione_t, _startTransazione_tea);
            System.out.println("startTransazione.result=" + _startTransazione__return);

        } catch (DaoException_Exception e) { 
            System.out.println("Expected exception: DaoException has occurred.");
            System.out.println(e.toString());
        } catch (NamingException_Exception e) { 
            System.out.println("Expected exception: NamingException has occurred.");
            System.out.println(e.toString());
        } catch (CreateException_Exception e) { 
            System.out.println("Expected exception: CreateException has occurred.");
            System.out.println(e.toString());
        } catch (MissingParameterException_Exception e) { 
            System.out.println("Expected exception: MissingParameterException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
