/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdp.mdpboweb.business.ws.coreCxf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Tue Mar 13 14:35:35 CET 2012
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "NamingException", targetNamespace = "http://interfacecxf.core.mdp.csi.it/")
public class NamingException_Exception extends Exception {
    public static final long serialVersionUID = 20120313143535L;
    
    private it.csi.mdp.mdpboweb.business.ws.coreCxf.NamingException namingException;

    public NamingException_Exception() {
        super();
    }
    
    public NamingException_Exception(String message) {
        super(message);
    }
    
    public NamingException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NamingException_Exception(String message, it.csi.mdp.mdpboweb.business.ws.coreCxf.NamingException namingException) {
        super(message);
        this.namingException = namingException;
    }

    public NamingException_Exception(String message, it.csi.mdp.mdpboweb.business.ws.coreCxf.NamingException namingException, Throwable cause) {
        super(message, cause);
        this.namingException = namingException;
    }

    public it.csi.mdp.mdpboweb.business.ws.coreCxf.NamingException getFaultInfo() {
        return this.namingException;
    }
}
