/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.sportello2epaywso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Sportello2EPaywso", targetNamespace = "http://www.csi.it/epay/epaywso/sportello2epaywso")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sportello2EPaywso {

    /**
     * 
     * @param parameters
     * @return
     */
    @WebMethod ( operationName = "TrasmettiRichiesteDiRevoca", action = "http://www.csi.it/epay/epaywso/service/TrasmettiRichiesteDiRevoca" )
    @WebResult ( name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters" )
    public ResponseType trasmettiRichiesteDiRevoca (
        @WebParam ( partName = "parameters", name = "TrasmettiRichiesteDiRevocaRequest",
                        targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types" ) TrasmettiRichiesteDiRevocaRequest parameters );

    /**
     * 
     * @param parameters
     * @return
     *     returns it.csi.sportello2epaywso.ResponseType
     */
    @WebMethod(operationName = "TrasmettiNotifichePagamento", action = "http://www.csi.it/epay/epaywso/service/TrasmettiNotifichePagamento")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public ResponseType trasmettiNotifichePagamento(
        @WebParam(name = "TrasmettiNotifichePagamentoRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types", partName = "parameters")
        TrasmettiNotifichePagamentoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns it.csi.sportello2epaywso.ResponseType
     */
    @WebMethod(operationName = "TrasmettiAvvisiScaduti", action = "http://www.csi.it/epay/epaywso/service/TrasmettiAvvisiScaduti")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public ResponseType trasmettiAvvisiScaduti(
        @WebParam(name = "TrasmettiAvvisiScadutiRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types", partName = "parameters")
        TrasmettiAvvisiScadutiRequest parameters);

}
