/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.epay.epayservices.ws.EPaywso2SportelloService;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EPaywso2SportelloService", targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywsosrv", wsdlLocation = "file:/D:/Sviluppo/prodotti/csi/workspace_ePay/epayservices/docs/wsdl/EPaywso2SportelloService.wsdl")
public class EPaywso2SportelloService_Service
    extends Service
{

    private final static URL EPAYWSO2SPORTELLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException EPAYWSO2SPORTELLOSERVICE_EXCEPTION;
    private final static QName EPAYWSO2SPORTELLOSERVICE_QNAME = new QName("http://www.csi.it/epay/epaywso/enti2epaywsosrv", "EPaywso2SportelloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Sviluppo/prodotti/csi/workspace_ePay/epayservices/docs/wsdl/EPaywso2SportelloService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPAYWSO2SPORTELLOSERVICE_WSDL_LOCATION = url;
        EPAYWSO2SPORTELLOSERVICE_EXCEPTION = e;
    }

    public EPaywso2SportelloService_Service() {
        super(__getWsdlLocation(), EPAYWSO2SPORTELLOSERVICE_QNAME);
    }

    public EPaywso2SportelloService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EPAYWSO2SPORTELLOSERVICE_QNAME, features);
    }

    public EPaywso2SportelloService_Service(URL wsdlLocation) {
        super(wsdlLocation, EPAYWSO2SPORTELLOSERVICE_QNAME);
    }

    public EPaywso2SportelloService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EPAYWSO2SPORTELLOSERVICE_QNAME, features);
    }

    public EPaywso2SportelloService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EPaywso2SportelloService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EPaywso2SportelloService
     */
    @WebEndpoint(name = "EPaywso2SportelloServiceSOAP")
    public EPaywso2SportelloService getEPaywso2SportelloServiceSOAP() {
        return super.getPort(new QName("http://www.csi.it/epay/epaywso/enti2epaywsosrv", "EPaywso2SportelloServiceSOAP"), EPaywso2SportelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EPaywso2SportelloService
     */
    @WebEndpoint(name = "EPaywso2SportelloServiceSOAP")
    public EPaywso2SportelloService getEPaywso2SportelloServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.csi.it/epay/epaywso/enti2epaywsosrv", "EPaywso2SportelloServiceSOAP"), EPaywso2SportelloService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPAYWSO2SPORTELLOSERVICE_EXCEPTION!= null) {
            throw EPAYWSO2SPORTELLOSERVICE_EXCEPTION;
        }
        return EPAYWSO2SPORTELLOSERVICE_WSDL_LOCATION;
    }

}
