/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.epay.epayservices.ws.EPaywso2SportelloService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EPaywso2SportelloService", targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywsosrv")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EPaywso2SportelloService {


    /**
     * 
     * @param parameters
     * @return
     *     returns it.csi.epay.epayservices.ws.EPaywso2SportelloService.InserisciListaDiCaricoResponse
     */
    @WebMethod(operationName = "InserisciListaDiCarico", action = "http://www.csi.it/epay/epaywso/service/InserisciListaDiCarico")
    @WebResult(name = "InserisciListaDiCaricoResponse", targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywso/types", partName = "parameters")
    public InserisciListaDiCaricoResponse inserisciListaDiCarico(
        @WebParam(name = "InserisciListaDiCaricoRequest", targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywso/types", partName = "parameters")
        InserisciListaDiCaricoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns it.csi.epay.epayservices.ws.EPaywso2SportelloService.AggiornaPosizioniDebitorieResponse
     */
    @WebMethod(operationName = "AggiornaPosizioniDebitorie", action = "http://www.csi.it/epay/epaywso/service/AggiornaPosizioniDebitorie")
    @WebResult(name = "AggiornaPosizioniDebitorieResponse", targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywso/types", partName = "parameters")
    public AggiornaPosizioniDebitorieResponse aggiornaPosizioniDebitorie(
        @WebParam(name = "AggiornaPosizioniDebitorieRequest", targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywso/types", partName = "parameters")
        AggiornaPosizioniDebitorieRequest parameters);

}
