/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.15 at 05:05:41 PM CEST 
//


package it.csi.mdp.core.business.dto.multicarrello;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiSingoloVersamentoRPT", propOrder = {
    "importoSingoloVersamento",
    "commissioneCaricoPA",
//    "ibanAccredito",
//    "bicAccredito",
//    "ibanAppoggio",
//    "bicAppoggio",
    "credenzialiPagatore",
    "causaleVersamento", // Descrizione causale versamento
    "datiSpecificiRiscossione",
    "datiMarcaBolloDigitale",
    "datiAccertamento"
})
public class DatiSingoloVersamentoRPT implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = -1949736849832735320L;
	@XmlElement(required = true)
    protected BigDecimal importoSingoloVersamento;
    protected BigDecimal commissioneCaricoPA;
    protected String credenzialiPagatore;
    @XmlElement(required = true)
    protected String causaleVersamento;
    @XmlElement(required = true)
    protected String datiSpecificiRiscossione;
    protected DatiMarcaBolloDigitale datiMarcaBolloDigitale;

    protected DatiAccertamentoRPT datiAccertamento; //TAG_PPU - 2019 - RDI 004 - RDI 005

    /**
     * Gets the value of the importoSingoloVersamento property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImportoSingoloVersamento() {
        return importoSingoloVersamento;
    }

    /**
     * Sets the value of the importoSingoloVersamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImportoSingoloVersamento(BigDecimal value) {
        this.importoSingoloVersamento = value;
    }

    /**
     * Gets the value of the commissioneCaricoPA property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCommissioneCaricoPA() {
        return commissioneCaricoPA;
    }

    /**
     * Sets the value of the commissioneCaricoPA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCommissioneCaricoPA(BigDecimal value) {
        this.commissioneCaricoPA = value;
    }

    /**
     * Gets the value of the credenzialiPagatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredenzialiPagatore() {
        return credenzialiPagatore;
    }

    /**
     * Sets the value of the credenzialiPagatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredenzialiPagatore(String value) {
        this.credenzialiPagatore = value;
    }

    /**
     * Gets the value of the causaleVersamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCausaleVersamento() {
        return causaleVersamento;
    }

    /**
     * Sets the value of the causaleVersamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCausaleVersamento(String value) {
        this.causaleVersamento = value;
    }

    /**
     * Gets the value of the datiSpecificiRiscossione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatiSpecificiRiscossione() {
        return datiSpecificiRiscossione;
    }

    /**
     * Sets the value of the datiSpecificiRiscossione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatiSpecificiRiscossione(String value) {
        this.datiSpecificiRiscossione = value;
    }

	public DatiMarcaBolloDigitale getDatiMarcaBolloDigitale() {
		return datiMarcaBolloDigitale;
	}

	public void setDatiMarcaBolloDigitale(
			DatiMarcaBolloDigitale datiMarcaBolloDigitale) {
		this.datiMarcaBolloDigitale = datiMarcaBolloDigitale;
	}

    /**
     * Gets the value of the datiMarcaBolloDigitale property.
     * 
     * @return
     *     possible object is
     *     {@link CtDatiMarcaBolloDigitale }
     *     
     */
    
    public DatiAccertamentoRPT getDatiAccertamento () {
        return datiAccertamento;
    }

    public void setDatiAccertamento ( DatiAccertamentoRPT datiAccertamento ) {
        this.datiAccertamento = datiAccertamento;
    }
}
