### https://tst-mdp.piemontepay.it/mdppagopacheckout/api/landingpages/v1/urlpaymentok?transactionId=TST000000004255071&macId=t9dZjUxAjUPa+zmz7UxK59E96oOXk97NNOV

GET {{bserURLLanding}}urlpaymentok?transactionId=TST000000004255071&macId=t9dZjUxAjUPa+zmz7UxK59E96oOXk97NNOV

### è sbagliato il + nel mac!!
### è sbagliato il + nel mac!!
### è sbagliato il + nel mac!!
### è sbagliato il + nel mac!!
### è sbagliato il + nel mac!!

