/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epayjob.business.epaypacatalogsrv;

import it.csi.epay.epayjob.interfacews.epaypacatalogsrv.Epaypacatalogsrv;
import org.apache.logging.log4j.LogManager;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-11-19T17:08:33.366+01:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "EpaypacatalogsrvService",
                  wsdlLocation = "http://dev-jboss5-epay.bilancio.csi.it:13010/epaypacatalogsrvApplEpaypacatalogsrvWs/EpaypacatalogsrvService?WSDL",
                  targetNamespace = "http://business.epaypacatalogsrv.epay.csi.it/")
public class EpaypacatalogsrvService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://business.epaypacatalogsrv.epay.csi.it/", "EpaypacatalogsrvService");
    public final static QName EpaypacatalogsrvPort = new QName("http://business.epaypacatalogsrv.epay.csi.it/", "EpaypacatalogsrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://dev-jboss5-epay.bilancio.csi.it:13010/epaypacatalogsrvApplEpaypacatalogsrvWs/EpaypacatalogsrvService?WSDL");
        } catch (MalformedURLException e) {
			LogManager.getLogger(EpaypacatalogsrvService.class.getName())
                .info(
                     "Can not initialize the default wsdl from {0}", "http://dev-jboss5-epay.bilancio.csi.it:13010/epaypacatalogsrvApplEpaypacatalogsrvWs/EpaypacatalogsrvService?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public EpaypacatalogsrvService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EpaypacatalogsrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpaypacatalogsrvService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EpaypacatalogsrvService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EpaypacatalogsrvService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EpaypacatalogsrvService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Epaypacatalogsrv
     */
    @WebEndpoint(name = "EpaypacatalogsrvPort")
    public Epaypacatalogsrv getEpaypacatalogsrvPort() {
        return super.getPort(EpaypacatalogsrvPort, Epaypacatalogsrv.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Epaypacatalogsrv
     */
    @WebEndpoint(name = "EpaypacatalogsrvPort")
    public Epaypacatalogsrv getEpaypacatalogsrvPort(WebServiceFeature... features) {
        return super.getPort(EpaypacatalogsrvPort, Epaypacatalogsrv.class, features);
    }

}
