/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaymodric.util.wsdl.flussorendicontazione;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2019-03-21T14:58:22.606+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.csi.it/epay/epaywso/rendicontazione-ext", name = "ServiziRendicontazioneExt")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiziRendicontazioneExt {

    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    @WebMethod(operationName = "TrasmettiFlussoRendicontazioneExt", action = "http://www.csi.it/epay/epaywso/rendicontazione-ext/TrasmettiFlussoRendicontazioneExt")
    public ResponseType trasmettiFlussoRendicontazioneExt(
        @WebParam(partName = "parameters", name = "TrasmettiFlussoRendicontazioneExtRequest", targetNamespace = "http://www.csi.it/epay/epaywso/rendicontazione-ext")
        TrasmettiFlussoRendicontazioneExtRequestType parameters
    );

    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    @WebMethod(operationName = "TrasmettiRT", action = "http://www.csi.it/epay/epaywso/rendicontazione-ext/TrasmettiRT")
    public ResponseType trasmettiRT(
        @WebParam(partName = "parameters", name = "TrasmettiRTExtRequest", targetNamespace = "http://www.csi.it/epay/epaywso/rendicontazione-ext")
        TrasmettiRTExtRequestType parameters
    );
}
