/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epayservices.model;

public enum ParamNameXPdf {
    A1_LOGO_ENTE,
    A2_LOGO_PAGOPA,
    B1_TITOLO,
    B2_DESCRIZIONE_TASSA,
    B3_STATO_TRANSAZIONE,
    C1_DESCRIZIONE_ENTE,
    C2_CF_ENTE,
    C3_IMPORTO,
    C4_CODICE_AVVISO,
    C5_IUV,
    C6_NOTE,
    D1_NOME,
    D2_CF,
    E1_ID_TRANSAZIONE,
    E2_DESCRIZIONE_PRESTATORE,
    E3_DATA_ORA,
    E3_DATA_ORA_OPERAZIONE,
    E3_DATA_APPLICATIVA,
	E3_DATA_ESITO_PAGAMENTO,
    E4_IDENTIFICATIVO_UNIVOCO_RISCOSSIONE,
    E5_ESITO_SINGOLO_PAGAMENTO,
    F1_GLN_CODE,
    Z1_PDFWRITER,
    C6_NOTE_PAGAMENTO,
    C6_CAUSALE,
    F1_DESCRIZIONE_ENTE_SECONDARIO,
    F2_CF_ENTE_SECONDARIO,
    F3_DESCRIZIONE_TASSA_SECONDARIO,
    F4_IMPORTO_PRINCIPALE,
    F4_IMPORTO_SECONDARIO;
}
