/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaypaweb.enumeration;

public enum ColumnNameFlussoEnum {
	ID_FLUSSO,
	ID_MESSAGGIO,
	TIPO_FLUSSO,
	DESCRIZIONE_TIPO_FLUSSO,
	STATO_FLUSSO,
	DESCRIZIONE_STATO_FLUSSO,
	ID_ENTE,
	ID_CODICE_VERSAMENTO,
	NUMERO_ELEMENTI,
	IMPORTO_TOTALE,
	PAGAMENTI_SPONTANEI,
	DATA_INSERIMENTO,
	DATA_ULTIMA_VARIAZIONE,
	UTENTE_ULTIMA_VARIAZIONE,
	CODICE_ESITO,
	DETTAGLIO_ESITO,
	DATA_REGOLAMENTO,
	TIPO_ID_MITTENTE,
	COD_ID_UNIVOCO_MITTENTE,
	DENOMINAZIONE_MITTENTE,
	IUV,
	C_FISC,
	IUV_AGGIORNAMENTO_POSIZIONI_DEBITORIE,
	POSIZIONE_DEBITORIA_ESTERNA,
}
