/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-10-24T15:04:56.710+02:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "EpaysimulatorDatawsService",
                  wsdlLocation = "file:/C:/Users/FGIUFF~1/AppData/Local/Temp/tempdir4589310248797512652.tmp/EpaysimulatorDatawsService_1.wsdl",
                  targetNamespace = "http://epaysim.business.epaysim.epay.csi.it/")
public class EpaysimulatorDatawsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://epaysim.business.epaysim.epay.csi.it/", "EpaysimulatorDatawsService");
    public final static QName EpaysimulatorDatawsPort = new QName("http://epaysim.business.epaysim.epay.csi.it/", "EpaysimulatorDatawsPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/FGIUFF~1/AppData/Local/Temp/tempdir4589310248797512652.tmp/EpaysimulatorDatawsService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EpaysimulatorDatawsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/FGIUFF~1/AppData/Local/Temp/tempdir4589310248797512652.tmp/EpaysimulatorDatawsService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EpaysimulatorDatawsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EpaysimulatorDatawsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpaysimulatorDatawsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EpaysimulatorDatawsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EpaysimulatorDatawsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EpaysimulatorDatawsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EpaysimulatorDataws
     */
    @WebEndpoint(name = "EpaysimulatorDatawsPort")
    public EpaysimulatorDataws getEpaysimulatorDatawsPort() {
        return super.getPort(EpaysimulatorDatawsPort, EpaysimulatorDataws.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EpaysimulatorDataws
     */
    @WebEndpoint(name = "EpaysimulatorDatawsPort")
    public EpaysimulatorDataws getEpaysimulatorDatawsPort(WebServiceFeature... features) {
        return super.getPort(EpaysimulatorDatawsPort, EpaysimulatorDataws.class, features);
    }

}
