/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-10-24T15:04:56.695+02:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", name = "EpaysimulatorDataws")
@XmlSeeAlso({ObjectFactory.class})
public interface EpaysimulatorDataws {

    @WebMethod
    @RequestWrapper(localName = "ricercaProvvisori", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaProvvisori")
    @ResponseWrapper(localName = "ricercaProvvisoriResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaProvvisoriResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.DtoOutputWsProvvisori ricercaProvvisori(
        @WebParam(name = "listaProvvisoriDaCercare", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.DtoInputWsRicercaProvvisori listaProvvisoriDaCercare
    ) throws EpaysimulatorException_Exception;

    @WebMethod
    @RequestWrapper ( localName = "giornaleDiCassa", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/",
                    className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.GiornaleDiCassa" )
    @ResponseWrapper ( localName = "giornaleDiCassaInputDTO", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/",
                    className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.GiornaleDiCassaResponse" )
    @WebResult ( name = "result", targetNamespace = "" )
    public GiornaleDiCassaOutputDTO ricercaGiornaleDiCassa (
        @WebParam ( partName = "parameters",
                        targetNamespace = "" ) it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.GiornaleDiCassaInputDTO parameters )
                    throws EpaysimulatorException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciProvvisorio", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.InserisciProvvisorio")
    @ResponseWrapper(localName = "inserisciProvvisorioResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.InserisciProvvisorioResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.InserisciProvvisorioOutputResponse inserisciProvvisorio(
        @WebParam(name = "param", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.InserisciProvvisorioInputDTO param
    ) throws EpaysimulatorException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateEsitoStatoElaborazioneFlusso", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.UpdateEsitoStatoElaborazioneFlusso")
    @ResponseWrapper(localName = "updateEsitoStatoElaborazioneFlussoResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.UpdateEsitoStatoElaborazioneFlussoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.UpdateEsitoStatoElaborazioneFlussoOutputDTO updateEsitoStatoElaborazioneFlusso(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.UpdateEsitoStatoElaborazioneFlussoInputDTO arg0
    ) throws EpaysimulatorException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaFlusso", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlusso")
    @ResponseWrapper(localName = "ricercaFlussoResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoOutputResponse ricercaFlusso(
        @WebParam(name = "param", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoInputDTO param
    ) throws DatatypeConfigurationException_Exception, EpaysimulatorException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaFlussoSintesiPagoPa", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoSintesiPagoPa")
    @ResponseWrapper(localName = "ricercaFlussoSintesiPagoPaResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoSintesiPagoPaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoSintesiPagopaOutputDTO ricercaFlussoSintesiPagoPa(
        @WebParam(name = "param", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoSintesiPagopaDTO param
    ) throws EpaysimulatorException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaFlussoDettaglioPagoPa", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoDettaglioPagoPa")
    @ResponseWrapper(localName = "ricercaFlussoDettaglioPagoPaResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoDettaglioPagoPaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoDettaglioPagopaOutputDTO ricercaFlussoDettaglioPagoPa(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoDettaglioPagopaDTO arg0
    ) throws EpaysimulatorException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaFlussiInErrore", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussiInErrore")
    @ResponseWrapper(localName = "ricercaFlussiInErroreResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussiInErroreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoOrigineErrorePagopaOutputDTO> ricercaFlussiInErrore(
        @WebParam(name = "param", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoErroreInputDTO param
    ) throws EpaysimulatorException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaFlussoOriginePagoPa", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoOriginePagoPa")
    @ResponseWrapper(localName = "ricercaFlussoOriginePagoPaResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaFlussoOriginePagoPaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoOriginePagopaOutputDTO ricercaFlussoOriginePagoPa(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoOriginePagopaDTO arg0
    ) throws EpaysimulatorException_Exception, UnrecoverableException_Exception, Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaDettaglioPagoPa", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaDettaglioPagoPa")
    @ResponseWrapper(localName = "ricercaDettaglioPagoPaResponse", targetNamespace = "http://epaysim.interfacews.epaysim.epay.csi.it/", className = "it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.RicercaDettaglioPagoPaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoDettaglioPagopaOutputDTO ricercaDettaglioPagoPa(
        @WebParam(name = "param", targetNamespace = "")
        it.csi.epay.epaysimweb.integration.stubs.epaysimulatordataws.FlussoDettaglioPagopaDTO param
    ) throws EpaysimulatorException_Exception;
}
