### servizio 2
POST {{baseURLAPI}}organizations/80087670016/citizens/SROLSN77S61C722O/paymenttypes/MC00/debtpositions
Authorization: Basic epayapi1 mypass
Accept: application/json
Content-Type: application/json

{
  "note": "posizione debitoria con campi valorizzati",
  "importo": 3,
  "nome": "pippo",
  "cognome": "pluto",
  "email": "aa@aa.it"
}

### risultato locale: connection timeout

### servizio 2
POST {{baseURLAPI}}organizations/80087670016/citizens/SROLSN77S61C722O/paymenttypes/NA00/debtpositions
Authorization: Basic epayapi1 mypass
Accept: application/json
Content-Type: application/json

{
  "note": "posizione debitoria TEST",
  "importo": 0,
  "nome": "pippo",
  "cognome": "pluto",
  "email": "aa@aa.it"
}

### risultato locale: connection timeout

GET http://tst-srv-pay.bilancio.csi.it/epayfe/api/v1/organizations/80087670016/citizens/PVSNTN31T15L219U/debtpositions
Authorization: Basic epayapi1 mypass
Accept: application/json
Content-Type: application/json

###

GET {{baseURLAPI}}organizations/80087670016/citizens/PVSNTN31T15L219U/debtpositions
Authorization: Basic epayapi1 mypass
Accept: application/json
Content-Type: application/json

###

POST http://tst-srv-pay.bilancio.csi.it/epayfe/api/v1/organizations/00125680033/citizens/GLLGLL64B15G702I/paymenttypes/DF40/debtpositions
Authorization: Basic epayapi1 mypass
Accept: application/json
Content-Type: application/json

{

}