/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdpiuv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MdpiuvWSInterface", targetNamespace = "http://mdpnew.csi.it/mdpiuv/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MdpiuvWSInterface {


    /**
     * 
     * @param idApplicazione
     * @param codicePagamento
     * @return
     *     returns it.csi.mdpiuv.IuvComplex
     * @throws MdpIuvSrvException_Exception
     * @throws UnrecoverableException_Exception
     * @throws CSIException_Exception
     * @throws SystemException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "iuvComplexResponse", partName = "iuvComplexResponse")
    public IuvComplex getSingleIUVComplex(
        @WebParam(name = "idApplicazione", partName = "idApplicazione")
        String idApplicazione,
        @WebParam(name = "codicePagamento", partName = "codicePagamento")
        String codicePagamento)
        throws CSIException_Exception, MdpIuvSrvException_Exception, SOAPException_Exception, SystemException_Exception, UnrecoverableException_Exception
    ;

    /**
     * 
     * @param idApplicazione
     * @param codicePagamento
     * @return
     *     returns java.lang.String
     * @throws MdpIuvSrvException_Exception
     * @throws UnrecoverableException_Exception
     * @throws CSIException_Exception
     * @throws SystemException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "iuv", partName = "iuv")
    public String getSingleIUV(
        @WebParam(name = "idApplicazione", partName = "idApplicazione")
        String idApplicazione,
        @WebParam(name = "codicePagamento", partName = "codicePagamento")
        String codicePagamento)
        throws CSIException_Exception, MdpIuvSrvException_Exception, SOAPException_Exception, SystemException_Exception, UnrecoverableException_Exception
    ;

    /**
     * 
     * @param idApplicazione
     * @param codicePagamento
     * @param numeroOccorrenzeIUV
     * @return
     *     returns it.csi.mdpiuv.IuvComplexArray
     * @throws MdpIuvSrvException_Exception
     * @throws UnrecoverableException_Exception
     * @throws CSIException_Exception
     * @throws SystemException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "iuvComplexResponse", partName = "iuvComplexResponse")
    public IuvComplexArray getMultiIUVComplex(
        @WebParam(name = "idApplicazione", partName = "idApplicazione")
        String idApplicazione,
        @WebParam(name = "codicePagamento", partName = "codicePagamento")
        String codicePagamento,
        @WebParam(name = "numeroOccorrenzeIUV", partName = "numeroOccorrenzeIUV")
        int numeroOccorrenzeIUV)
        throws CSIException_Exception, MdpIuvSrvException_Exception, SOAPException_Exception, SystemException_Exception, UnrecoverableException_Exception
    ;

    /**
     * 
     * @param idApplicazione
     * @param codicePagamento
     * @param numeroOccorrenzeIUV
     * @return
     *     returns it.csi.mdpiuv.StringArray
     * @throws MdpIuvSrvException_Exception
     * @throws UnrecoverableException_Exception
     * @throws CSIException_Exception
     * @throws SystemException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "listaIuv", partName = "listaIuv")
    public StringArray getMultiIUV(
        @WebParam(name = "idApplicazione", partName = "idApplicazione")
        String idApplicazione,
        @WebParam(name = "numeroOccorrenzeIUV", partName = "numeroOccorrenzeIUV")
        int numeroOccorrenzeIUV,
        @WebParam(name = "codicePagamento", partName = "codicePagamento")
        String codicePagamento)
        throws CSIException_Exception, MdpIuvSrvException_Exception, SOAPException_Exception, SystemException_Exception, UnrecoverableException_Exception
    ;

}
