/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdpiuv;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MdpIuvSrvException", targetNamespace = "http://mdpnew.csi.it/mdpiuv/")
public class MdpIuvSrvException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MdpIuvSrvException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MdpIuvSrvException_Exception(String message, MdpIuvSrvException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MdpIuvSrvException_Exception(String message, MdpIuvSrvException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.csi.mdpiuv.MdpIuvSrvException
     */
    public MdpIuvSrvException getFaultInfo() {
        return faultInfo;
    }

}
