/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdpiuv;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MdpiuvWSInterface", targetNamespace = "http://mdpnew.csi.it/mdpiuv/", wsdlLocation = "http://tst-applogic.reteunitaria.piemonte.it/mdpiuv/MdpiuvsrvServiceWS?wsdl")
public class MdpiuvWSInterface_Service
    extends Service
{

    private final static URL MDPIUVWSINTERFACE_WSDL_LOCATION;
    private final static WebServiceException MDPIUVWSINTERFACE_EXCEPTION;
    private final static QName MDPIUVWSINTERFACE_QNAME = new QName("http://mdpnew.csi.it/mdpiuv/", "MdpiuvWSInterface");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tst-applogic.reteunitaria.piemonte.it/mdpiuv/MdpiuvsrvServiceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MDPIUVWSINTERFACE_WSDL_LOCATION = url;
        MDPIUVWSINTERFACE_EXCEPTION = e;
    }

    public MdpiuvWSInterface_Service() {
        super(__getWsdlLocation(), MDPIUVWSINTERFACE_QNAME);
    }

    public MdpiuvWSInterface_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MDPIUVWSINTERFACE_QNAME, features);
    }

    public MdpiuvWSInterface_Service(URL wsdlLocation) {
        super(wsdlLocation, MDPIUVWSINTERFACE_QNAME);
    }

    public MdpiuvWSInterface_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MDPIUVWSINTERFACE_QNAME, features);
    }

    public MdpiuvWSInterface_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MdpiuvWSInterface_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MdpiuvWSInterface
     */
    @WebEndpoint(name = "MdpiuvWSPort")
    public MdpiuvWSInterface getMdpiuvWSPort() {
        return super.getPort(new QName("http://mdpnew.csi.it/mdpiuv/", "MdpiuvWSPort"), MdpiuvWSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MdpiuvWSInterface
     */
    @WebEndpoint(name = "MdpiuvWSPort")
    public MdpiuvWSInterface getMdpiuvWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdpnew.csi.it/mdpiuv/", "MdpiuvWSPort"), MdpiuvWSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MDPIUVWSINTERFACE_EXCEPTION!= null) {
            throw MDPIUVWSINTERFACE_EXCEPTION;
        }
        return MDPIUVWSINTERFACE_WSDL_LOCATION;
    }

}
