/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epayfeapi.soap.client.mdp.core.interfacecxf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-03-15T20:45:31.043+01:00
 * Generated source version: 3.3.0
 */

@WebFault ( name = "MissingParameterException", targetNamespace = "http://interfacecxf.core.mdp.csi.it/" )
@SuppressWarnings ( "unused" )
public class MissingParameterException_Exception extends Exception {

	public static final long serialVersionUID = 1L;

	private MissingParameterException missingParameterException;

	public MissingParameterException_Exception () {
		super ();
	}

	public MissingParameterException_Exception ( String message ) {
		super ( message );
	}

	public MissingParameterException_Exception ( String message, Throwable cause ) {
		super ( message, cause );
	}

	public MissingParameterException_Exception ( String message, MissingParameterException missingParameterException ) {
		super ( message );
		this.missingParameterException = missingParameterException;
	}

	public MissingParameterException_Exception ( String message, MissingParameterException missingParameterException, Throwable cause ) {
		super ( message, cause );
		this.missingParameterException = missingParameterException;
	}

	public MissingParameterException getFaultInfo () {
		return this.missingParameterException;
	}
}
