GET {{baseURLAPI}}organizations/00125680033/citizens/LVLDAA85T50G702B/debtpositions
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json

###

GET {{baseURLAPI}}organizations/00125680033/citizens/PPPPPP64B15G702I/debtpositions?status=NOT_PAYED
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json

###

GET {{baseURLAPI}}organizations/00125680033/citizens/LVLDAA85T50G702B/debtpositions?currentPage=1&elements=10&iuv=20230931805530133&sort=-dataOraOperazione
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json

###

GET {{baseURLAPI}}organizations/00125680033/citizens/LVLDAA85T50G702B/debtpositions?currentPage=1&elements=10&iuv=20230931805530133
Authorization: Basic {{user}} {{pass}}
Accept: application/json
Content-Type: application/json

###

