/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.epay.epayjob.interfacews.epaypacatalogsrv;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2018-11-23T11:10:47.442+01:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "EpaypacatalogsrvException", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/")
public class EpaypacatalogsrvException_Exception extends java.lang.Exception {
    
    private it.csi.epay.epayjob.interfacews.epaypacatalogsrv.EpaypacatalogsrvException epaypacatalogsrvException;

    public EpaypacatalogsrvException_Exception() {
        super();
    }
    
    public EpaypacatalogsrvException_Exception(String message) {
        super(message);
    }
    
    public EpaypacatalogsrvException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EpaypacatalogsrvException_Exception(String message, it.csi.epay.epayjob.interfacews.epaypacatalogsrv.EpaypacatalogsrvException epaypacatalogsrvException) {
        super(message);
        this.epaypacatalogsrvException = epaypacatalogsrvException;
    }

    public EpaypacatalogsrvException_Exception(String message, it.csi.epay.epayjob.interfacews.epaypacatalogsrv.EpaypacatalogsrvException epaypacatalogsrvException, Throwable cause) {
        super(message, cause);
        this.epaypacatalogsrvException = epaypacatalogsrvException;
    }

    public it.csi.epay.epayjob.interfacews.epaypacatalogsrv.EpaypacatalogsrvException getFaultInfo() {
        return this.epaypacatalogsrvException;
    }
}
