#Servizio nr7- PagamentoPosDeb(GET)
#
#code: "BUSINESS_ERROR"
#detail: "[getPaymentUrl] Codice Iuv riferito a pagamento effettuato, annullato, in attesa di ricevuta, non piu' valido perché scaduto oppure non trovato."
#status: "400"
#
#curl 'https://ts-servizi-novara.portali.csi.it/api/ppay/debtpositions/320230891805246353/payment' \
#  -H 'Accept: application/json, text/plain, */*' \
#  -H 'Accept-Language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7' \
#  -H 'Connection: keep-alive' \
#  -H 'Cookie: PORTALE=INTERNET_RUPAR; _shibstate_1681393800_451e_fgwars=https%3A%2F%2Fts-servizi-novara.portali.csi.it%2Fapi%2Futenti%2Fme; _shibstate_1681393800_451e=https%3A%2F%2Fts-servizi-novara.portali.csi.it%2Fapi%2Futenti%2Fme; _opensaml_req_cookie%3A1681393800_451e_fgwars=_705493628282f456ad214086015ef152; _opensaml_req_cookie%3A1681393800_451e=_705493628282f456ad214086015ef152; _shibsession_ts-ser-no_443sliv1spid_gasp4cifa_fgwars=_b99210e26ca0b59c9bcbddb23d95d3af; _shibsession_ts-ser-no_443sliv1spid_gasp4cifa=_b99210e26ca0b59c9bcbddb23d95d3af' \
#  -H 'Referer: https://ts-servizi-novara.portali.csi.it/area-personale/pagamento-iuv/320230891805246353' \
#  -H 'Sec-Fetch-Dest: empty' \
#  -H 'Sec-Fetch-Mode: cors' \
#  -H 'Sec-Fetch-Site: same-origin' \
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' \
#  -H 'sec-ch-ua: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"' \
#  -H 'sec-ch-ua-mobile: ?0' \
#  -H 'sec-ch-ua-platform: "Windows"' \
#  --compressed

GET {{baseURLAPI}}organizations/{{ofsRegionePiemonte}}/debtpositions/{{iuvPagabile}}/payment
Authorization: Basic {{user}} {{pass}}
Accept: application/json