/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epayfeapi.soap.client.mdpiuv;

import it.csi.epay.epayfeapi.soap.client.jaxb.array.StringArray;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-03-09T15:15:50.387+01:00
 * Generated source version: 3.3.0
 */
@WebService ( targetNamespace = "http://mdpnew.csi.it/mdpiuv/", name = "MdpiuvWSInterface" )
@XmlSeeAlso ( { ObjectFactory.class, it.csi.epay.epayfeapi.soap.client.jaxb.array.ObjectFactory.class } )
@SOAPBinding ( style = SOAPBinding.Style.RPC )
public interface MdpiuvWSInterface {

	@WebMethod
	@WebResult ( name = "iuvComplexResponse", targetNamespace = "http://mdpnew.csi.it/mdpiuv/", partName = "iuvComplexResponse" )
	IuvComplex getSingleIUVComplex (
					@WebParam ( partName = "idApplicazione", name = "idApplicazione" )
					String idApplicazione,
					@WebParam ( partName = "codicePagamento", name = "codicePagamento" )
					String codicePagamento
	);

	@WebMethod
	@WebResult ( name = "listaIuv", targetNamespace = "http://mdpnew.csi.it/mdpiuv/", partName = "listaIuv" )
	StringArray getMultiIUV (
					@WebParam ( partName = "idApplicazione", name = "idApplicazione" )
					String idApplicazione,
					@WebParam ( partName = "numeroOccorrenzeIUV", name = "numeroOccorrenzeIUV" )
					int numeroOccorrenzeIUV,
					@WebParam ( partName = "codicePagamento", name = "codicePagamento" )
					String codicePagamento
	);

	@WebMethod
	@WebResult ( name = "iuv", targetNamespace = "http://mdpnew.csi.it/mdpiuv/", partName = "iuv" )
	String getSingleIUV (
					@WebParam ( partName = "idApplicazione", name = "idApplicazione" )
					String idApplicazione,
					@WebParam ( partName = "codicePagamento", name = "codicePagamento" )
					String codicePagamento
	);

	@WebMethod
	@WebResult ( name = "iuvComplexResponse", targetNamespace = "http://mdpnew.csi.it/mdpiuv/", partName = "iuvComplexResponse" )
	IuvComplexArray getMultiIUVComplex (
					@WebParam ( partName = "idApplicazione", name = "idApplicazione" )
					String idApplicazione,
					@WebParam ( partName = "codicePagamento", name = "codicePagamento" )
					String codicePagamento,
					@WebParam ( partName = "numeroOccorrenzeIUV", name = "numeroOccorrenzeIUV" )
					int numeroOccorrenzeIUV
	);
}
