/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.08.31 at 04:23:55 PM CEST
//


package it.csi.epay.epaysim.dto;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for provvisorioDTO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="provvisorioDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="annoEsercizio" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="annoProvvisorio" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="causale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="codiceFiscaleEnte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="utenteInsVar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataInsVar" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dataMovimento" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="identificativoFlusso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="importoProvvisorio" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="numeroProvvisorio" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "provvisorioDTO", propOrder = {
    "annoEsercizio",
    "annoProvvisorio",
    "causale",
    "codiceFiscaleEnte",
    "utenteInsVar",
    "dataInsVar",
    "dataMovimento",
    "id",
    "identificativoFlusso",
    "importoProvvisorio",
    "numeroProvvisorio",
    "stato",
    "idGiornaleDiCassa",
    "utenteModifica",
    "dataModifica"
})
public class ProvvisorioDTO {

    protected Integer annoEsercizio;
    protected Integer annoProvvisorio;
    protected String causale;
    protected String codiceFiscaleEnte;
    protected String utenteInsVar;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataInsVar;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataMovimento;
    protected Long id;
    protected String identificativoFlusso;
    protected BigDecimal importoProvvisorio;
    protected Integer numeroProvvisorio;
    protected String stato;

    protected Integer idGiornaleDiCassa;

    protected String utenteModifica;

    @XmlSchemaType ( name = "dateTime" )
    protected XMLGregorianCalendar dataModifica;

    /**
     * Gets the value of the annoEsercizio property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getAnnoEsercizio() {
        return annoEsercizio;
    }

    /**
     * Sets the value of the annoEsercizio property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setAnnoEsercizio(Integer value) {
        this.annoEsercizio = value;
    }

    /**
     * Gets the value of the annoProvvisorio property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getAnnoProvvisorio() {
        return annoProvvisorio;
    }

    /**
     * Sets the value of the annoProvvisorio property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setAnnoProvvisorio(Integer value) {
        this.annoProvvisorio = value;
    }

    /**
     * Gets the value of the causale property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCausale() {
        return causale;
    }

    /**
     * Sets the value of the causale property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCausale(String value) {
        this.causale = value;
    }

    /**
     * Gets the value of the codiceFiscaleEnte property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodiceFiscaleEnte() {
        return codiceFiscaleEnte;
    }

    /**
     * Sets the value of the codiceFiscaleEnte property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodiceFiscaleEnte(String value) {
        this.codiceFiscaleEnte = value;
    }

    /**
     * Gets the value of the utenteInsVar property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUtenteInsVar() {
        return utenteInsVar;
    }

    /**
     * Sets the value of the utenteInsVar property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUtenteInsVar(String value) {
        this.utenteInsVar = value;
    }

    /**
     * Gets the value of the dataInsVar property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataInsVar() {
        return dataInsVar;
    }

    /**
     * Sets the value of the dataInsVar property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataInsVar(XMLGregorianCalendar value) {
        this.dataInsVar = value;
    }

    /**
     * Gets the value of the dataMovimento property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataMovimento() {
        return dataMovimento;
    }

    /**
     * Sets the value of the dataMovimento property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataMovimento(XMLGregorianCalendar value) {
        this.dataMovimento = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the identificativoFlusso property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdentificativoFlusso() {
        return identificativoFlusso;
    }

    /**
     * Sets the value of the identificativoFlusso property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdentificativoFlusso(String value) {
        this.identificativoFlusso = value;
    }

    /**
     * Gets the value of the importoProvvisorio property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getImportoProvvisorio() {
        return importoProvvisorio;
    }

    /**
     * Sets the value of the importoProvvisorio property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setImportoProvvisorio(BigDecimal value) {
        this.importoProvvisorio = value;
    }

    /**
     * Gets the value of the numeroProvvisorio property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getNumeroProvvisorio() {
        return numeroProvvisorio;
    }

    /**
     * Sets the value of the numeroProvvisorio property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setNumeroProvvisorio(Integer value) {
        this.numeroProvvisorio = value;
    }

    /**
     * Gets the value of the stato property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStato() {
        return stato;
    }

    /**
     * Sets the value of the stato property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStato(String value) {
        this.stato = value;
    }

    public Integer getIdGiornaleDiCassa () {
        return idGiornaleDiCassa;
    }

    public void setIdGiornaleDiCassa ( Integer idGiornaleDiCassa ) {
        this.idGiornaleDiCassa = idGiornaleDiCassa;
    }

    public String getUtenteModifica () {
        return utenteModifica;
    }

    public void setUtenteModifica ( String utenteModifica ) {
        this.utenteModifica = utenteModifica;
    }

    public XMLGregorianCalendar getDataModifica () {
        return dataModifica;
    }

    public void setDataModifica ( XMLGregorianCalendar dataModifica ) {
        this.dataModifica = dataModifica;
    }

}
