POST {{baseURLAPI}}organizations/80087670016/paymenttypes/CC00/payment
Authorization: Basic {{epayapi1}} {{pass}}
Content-Type: application/json
Accept: application/json

{
  "note": "posizione debitoria servizio 6",
  "importo": 2.00,
  "nome": "pippo",
  "cognome": "pluto",
  "codiceFiscalePartitaIVAPagatore": "RTNLSN00E00L219X",
  "email": "aa@aa.it"
}

###