/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.mdp.mdppagopaapi.pa.pafornode_wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Dec 13 11:44:34 CET 2021
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.wsdl", name = "Mdpapisrv")
@XmlSeeAlso({it.csi.mdp.mdppagopaapi.pa.pafornode.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaForNodePortType {

    @WebMethod(action = "paSendRT")
    @WebResult(name = "paSendRTRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "responseBody")
    public it.csi.mdp.mdppagopaapi.pa.pafornode.PaSendRTRes paSendRT(
        @WebParam(partName = "requestBody", name = "paSendRTReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        it.csi.mdp.mdppagopaapi.pa.pafornode.PaSendRTReq requestBody
    );

    @WebMethod(action = "paVerifyPaymentNotice")
    @WebResult(name = "paVerifyPaymentNoticeRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "responseBody")
    public it.csi.mdp.mdppagopaapi.pa.pafornode.PaVerifyPaymentNoticeRes paVerifyPaymentNotice(
        @WebParam(partName = "requestBody", name = "paVerifyPaymentNoticeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        it.csi.mdp.mdppagopaapi.pa.pafornode.PaVerifyPaymentNoticeReq requestBody
    );

    @WebMethod(action = "paGetPayment")
    @WebResult(name = "paGetPaymentRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "responseBody")
    public it.csi.mdp.mdppagopaapi.pa.pafornode.PaGetPaymentRes paGetPayment(
        @WebParam(partName = "requestBody", name = "paGetPaymentReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        it.csi.mdp.mdppagopaapi.pa.pafornode.PaGetPaymentReq requestBody
    );
}
