/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epayfeapi.soap.client.mdpmultiiuv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-03-16T17:53:25.618+01:00
 * Generated source version: 3.3.0
 */
@WebService ( targetNamespace = "http://mdpnew.csi.it/mdpmultiiuv/", name = "MdpMultiIuvWSInterface" )
@XmlSeeAlso ( { ObjectFactory.class } )
@SOAPBinding ( style = SOAPBinding.Style.RPC )
public interface MdpMultiIuvWSInterface {

	@WebMethod
	@WebResult ( name = "ListaIuvComplex", targetNamespace = "http://mdpnew.csi.it/mdpmultiiuv/", partName = "ListaIuvComplex" )
	IuvComplexResponse getIuvComplex (
					@WebParam ( partName = "idApplicazione", name = "idApplicazione" )
					java.lang.String idApplicazione,
					@WebParam ( partName = "codicePagamento", name = "codicePagamento" )
					java.lang.String codicePagamento,
					@WebParam ( partName = "numeroOccorrenzeIUV", name = "numeroOccorrenzeIUV" )
					int numeroOccorrenzeIUV,
					@WebParam ( partName = "timeStamp", name = "timeStamp" )
					java.lang.String timeStamp,
					@WebParam ( partName = "mac", name = "mac" )
					java.lang.String mac
	);
}
