/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaypacatalogsrv.integration.stubs.richiediapplicationid;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2020-03-24T18:32:10.035+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.csi.it/epay/epaywso/richiediapplicationid", name = "RichiediApplicationId")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RichiediApplicationId {

    @WebMethod(operationName = "RichiediApplicationId", action = "http://www.csi.it/epay/epaywso/richiediapplicationid/RichiediApplicationId")
    @WebResult(name = "RichiediApplicationIdResponse", targetNamespace = "http://www.csi.it/epay/epaywso/richiediapplicationid", partName = "parameters")
    public RichiediApplicationIdResponse richiediApplicationId(
        @WebParam(partName = "parameters", name = "RichiediApplicationIdRequest", targetNamespace = "http://www.csi.it/epay/epaywso/richiediapplicationid")
        RichiediApplicationIdRequest parameters
    );
}
