/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.epay.epaypacatalogsrv.integration.stubs.richiediapplicationid;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2019-11-19T16:41:48.541+01:00
 * Generated source version: 2.4.6
 * 
 */
public final class RichiediApplicationId_RichiediApplicationId_Client {

    private static final QName SERVICE_NAME = new QName("http://www.csi.it/epay/epaywso/richiediapplicationid", "RichiediApplicationId");

    private RichiediApplicationId_RichiediApplicationId_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RichiediApplicationId_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RichiediApplicationId_Service ss = new RichiediApplicationId_Service(wsdlURL, SERVICE_NAME);
        RichiediApplicationId port = ss.getRichiediApplicationId();  
        
        {
        System.out.println("Invoking richiediApplicationId...");
        it.csi.epay.epaypacatalogsrv.integration.stubs.richiediapplicationid.RichiediApplicationIdRequest _richiediApplicationId_parameters = new RichiediApplicationIdRequest ();
        
        _richiediApplicationId_parameters.setCodiceFiscaleEnte ( "01000000000" );
        _richiediApplicationId_parameters.setIbanEnte ( "IT50L5792331405979331098685" );
        
        it.csi.epay.epaypacatalogsrv.integration.stubs.richiediapplicationid.RichiediApplicationIdResponse _richiediApplicationId__return = port.richiediApplicationId(_richiediApplicationId_parameters);
        System.out.println("richiediApplicationId.result=" + _richiediApplicationId__return.applicationId);


        }

        System.exit(0);
    }

}
