/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.epay.epaymdpservices.webservices.interfaces;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Dec 14 16:19:15 CET 2015
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "VerificaDatiPagamentoException", targetNamespace = "http://serviziofruitore.interfacews.mdp.nodospc.csi.it/")
public class VerificaDatiPagamentoException extends Exception {
    public static final long serialVersionUID = 20151214161915L;
    
    private VerificaDatiPagamentoExceptionInfo verificaDatiPagamentoException;

    public VerificaDatiPagamentoException() {
        super();
    }
    
    public VerificaDatiPagamentoException(String message) {
        super(message);
    }
    
    public VerificaDatiPagamentoException(String message, Throwable cause) {
        super(message, cause);
    }

    public VerificaDatiPagamentoException(String message, VerificaDatiPagamentoExceptionInfo verificaDatiPagamentoException) {
        super(message);
        this.verificaDatiPagamentoException = verificaDatiPagamentoException;
    }

    public VerificaDatiPagamentoException(String message, VerificaDatiPagamentoExceptionInfo verificaDatiPagamentoException, Throwable cause) {
        super(message, cause);
        this.verificaDatiPagamentoException = verificaDatiPagamentoException;
    }

    public VerificaDatiPagamentoExceptionInfo getFaultInfo() {
        return this.verificaDatiPagamentoException;
    }
}
