/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.epay.epaymodric.util.wsdl.coopapplicativapec;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;



/**
 * This class was generated by Apache CXF 2.4.6
 * 2019-02-05T16:43:09.307+01:00
 * Generated source version: 2.4.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "CoopApplicativaPEC",
                      portName = "CoopApplicativaPEC",
                      targetNamespace = "http://www.csi.it/epay/epaywso/coopapplicativapec",
                      wsdlLocation = "http://localhost:8081/epaypaweb-business/CoopApplicativaPEC/CoopApplicativaPEC?wsdl",
                      endpointInterface = "it.csi.epay.epaymodric.util.wsdl.coopapplicativapec.CoopApplicativaPEC")
                      
public class CoopApplicativaPECImpl implements CoopApplicativaPEC {

    private static final Logger LOG = LogManager.getLogger(CoopApplicativaPECImpl.class.getName());

}
