/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaymodric.util.wsdl.coopapplicativapec;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2019-02-05T16:43:09.322+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.csi.it/epay/epaywso/coopapplicativapec", name = "CoopApplicativaPEC")
@XmlSeeAlso({ObjectFactory.class})
public interface CoopApplicativaPEC {
}
