/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.mdpiuv;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnrecoverableException", targetNamespace = "http://mdpnew.csi.it/mdpiuv/")
public class UnrecoverableException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnrecoverableException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UnrecoverableException_Exception(String message, UnrecoverableException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UnrecoverableException_Exception(String message, UnrecoverableException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.csi.mdpiuv.UnrecoverableException
     */
    public UnrecoverableException getFaultInfo() {
        return faultInfo;
    }

}
