/*
* SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2019-06-18T21:33:04.627+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", name = "Epaypacatalogsrv")
@XmlSeeAlso({ObjectFactory.class})
public interface Epaypacatalogsrv {

    @WebMethod
    @RequestWrapper(localName = "elaboraCodaEmail", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.ElaboraCodaEmail")
    @ResponseWrapper(localName = "elaboraCodaEmailResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.ElaboraCodaEmailResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.ElaboraCodaEmailOutput elaboraCodaEmail(
        @WebParam(name = "elaboraCodaEmailInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.ElaboraCodaEmailInput elaboraCodaEmailInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProfilazioneUtenteCorrente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetProfilazioneUtenteCorrente")
    @ResponseWrapper(localName = "getProfilazioneUtenteCorrenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetProfilazioneUtenteCorrenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetProfilazioneUtenteCorrenteOutput getProfilazioneUtenteCorrente(
        @WebParam(name = "getProfilazioneUtenteCorrenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetProfilazioneUtenteCorrenteInput getProfilazioneUtenteCorrenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniPeriodicitaSchedulazioneRiconciliazione", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniPeriodicitaSchedulazioneRiconciliazione")
    @ResponseWrapper(localName = "getOpzioniPeriodicitaSchedulazioneRiconciliazioneResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniPeriodicitaSchedulazioneRiconciliazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniPeriodicitaSchedulazioneRiconciliazioneOutput getOpzioniPeriodicitaSchedulazioneRiconciliazione(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetUtente")
    @ResponseWrapper(localName = "getUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetUtenteOutput getUtente(
        @WebParam(name = "getUtenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetUtenteInput getUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaUtente")
    @ResponseWrapper(localName = "ricercaUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaUtenteOutput ricercaUtente(
        @WebParam(name = "ricercaUtenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaUtenteInput ricercaUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessaggi", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetMessaggi")
    @ResponseWrapper(localName = "getMessaggiResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetMessaggiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetMessaggiOutput getMessaggi(
        @WebParam(name = "getMessaggiInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetMessaggiInput getMessaggiInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaRiferimentoContabile")
    @ResponseWrapper(localName = "ricercaRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaRiferimentoContabileOutput ricercaRiferimentoContabile(
        @WebParam(name = "ricercaRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaRiferimentoContabileInput ricercaRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "autorizzaEsportazioneDati", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AutorizzaEsportazioneDati")
    @ResponseWrapper(localName = "autorizzaEsportazioneDatiResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AutorizzaEsportazioneDatiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AutorizzaEsportazioneDatiOutput autorizzaEsportazioneDati(
        @WebParam(name = "autorizzaEsportazioneDatiInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AutorizzaEsportazioneDatiInput autorizzaEsportazioneDatiInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTematica", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTematica")
    @ResponseWrapper(localName = "getOpzioniTematicaResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTematicaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTematicaOutput getOpzioniTematica(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniAssociazioneUtenteCdu", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniAssociazioneUtenteCdu")
    @ResponseWrapper(localName = "getOpzioniAssociazioneUtenteCduResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniAssociazioneUtenteCduResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniAssociazioneUtenteCduOutput getOpzioniAssociazioneUtenteCdu(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetRiferimentoContabile")
    @ResponseWrapper(localName = "getRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetRiferimentoContabileOutput getRiferimentoContabile(
        @WebParam(name = "getRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetRiferimentoContabileInput getRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEnte", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetEnte")
    @ResponseWrapper(localName = "getEnteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetEnteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetEnteOutput getEnte(
        @WebParam(name = "getEnteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetEnteInput getEnteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniAssociazioneUtenteTematica", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniAssociazioneUtenteTematica")
    @ResponseWrapper(localName = "getOpzioniAssociazioneUtenteTematicaResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniAssociazioneUtenteTematicaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniAssociazioneUtenteTematicaOutput getOpzioniAssociazioneUtenteTematica(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetCodiceVersamento")
    @ResponseWrapper(localName = "getCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetCodiceVersamentoOutput getCodiceVersamento(
        @WebParam(name = "getCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetCodiceVersamentoInput getCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTipologiaDatoSpecificoRiscossione", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipologiaDatoSpecificoRiscossione")
    @ResponseWrapper(localName = "getOpzioniTipologiaDatoSpecificoRiscossioneResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipologiaDatoSpecificoRiscossioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipologiaDatoSpecificoRiscossioneOutput getOpzioniTipologiaDatoSpecificoRiscossione(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciCodiceVersamento")
    @ResponseWrapper(localName = "inserisciCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciCodiceVersamentoOutput inserisciCodiceVersamento(
        @WebParam(name = "inserisciCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciCodiceVersamentoInput inserisciCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eliminaUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaUtente")
    @ResponseWrapper(localName = "eliminaUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaUtenteOutput eliminaUtente(
        @WebParam(name = "eliminaUtenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaUtenteInput eliminaUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProfilazioneUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetProfilazioneUtente")
    @ResponseWrapper(localName = "getProfilazioneUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetProfilazioneUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetProfilazioneUtenteOutput getProfilazioneUtente(
        @WebParam(name = "getProfilazioneUtenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetProfilazioneUtenteInput getProfilazioneUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eseguiMigrazione", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EseguiMigrazione")
    @ResponseWrapper(localName = "eseguiMigrazioneResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EseguiMigrazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EseguiMigrazioneOutput eseguiMigrazione(
        @WebParam(name = "eseguiMigrazioneInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EseguiMigrazioneInput eseguiMigrazioneInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniStatoAggiornamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniStatoAggiornamento")
    @ResponseWrapper(localName = "getOpzioniStatoAggiornamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniStatoAggiornamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniStatoAggiornamentoOutput getOpzioniStatoAggiornamento(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    );

    @WebMethod
    @RequestWrapper(localName = "ricercaVoceEntrata", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaVoceEntrata")
    @ResponseWrapper(localName = "ricercaVoceEntrataResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaVoceEntrataResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaVoceEntrataOutput ricercaVoceEntrata(
        @WebParam(name = "ricercaVoceEntrataInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaVoceEntrataInput ricercaVoceEntrataInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaRiferimentoContabile")
    @ResponseWrapper(localName = "aggiornaRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaRiferimentoContabileOutput aggiornaRiferimentoContabile(
        @WebParam(name = "aggiornaRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaRiferimentoContabileInput aggiornaRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniStatoAggiornamentoEnte", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniStatoAggiornamentoEnte")
    @ResponseWrapper(localName = "getOpzioniStatoAggiornamentoEnteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniStatoAggiornamentoEnteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniStatoAggiornamentoEnteOutput getOpzioniStatoAggiornamentoEnte(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "chiudiRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.ChiudiRiferimentoContabile")
    @ResponseWrapper(localName = "chiudiRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.ChiudiRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.ChiudiRiferimentoContabileOutput chiudiRiferimentoContabile(
        @WebParam(name = "chiudiRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.ChiudiRiferimentoContabileInput chiudiRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaCodiceVersamento")
    @ResponseWrapper(localName = "ricercaCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaCodiceVersamentoOutput ricercaCodiceVersamento(
        @WebParam(name = "ricercaCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaCodiceVersamentoInput ricercaCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaVoceEntrataDisponibile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaVoceEntrataDisponibile")
    @ResponseWrapper(localName = "ricercaVoceEntrataDisponibileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaVoceEntrataDisponibileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaVoceEntrataDisponibileOutput ricercaVoceEntrataDisponibile(
        @WebParam(name = "ricercaVoceEntrataDisponibileInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.RicercaVoceEntrataDisponibileInput ricercaVoceEntrataDisponibileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaTematicheUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaTematicheUtente")
    @ResponseWrapper(localName = "aggiornaTematicheUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaTematicheUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaTematicheUtenteOutput aggiornaTematicheUtente(
        @WebParam(name = "aggiornaTematicheUtenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaTematicheUtenteInput aggiornaTematicheUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniModalitaAcquisizioneProvvisori", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniModalitaAcquisizioneProvvisori")
    @ResponseWrapper(localName = "getOpzioniModalitaAcquisizioneProvvisoriResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniModalitaAcquisizioneProvvisoriResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniModalitaAcquisizioneProvvisoriOutput getOpzioniModalitaAcquisizioneProvvisori(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaEnte", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaEnte")
    @ResponseWrapper(localName = "aggiornaEnteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaEnteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaEnteOutput aggiornaEnte(
        @WebParam(name = "modificaEnteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaEnteInput modificaEnteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciRiferimentoContabile")
    @ResponseWrapper(localName = "inserisciRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciRiferimentoContabileOutput inserisciRiferimentoContabile(
        @WebParam(name = "inserisciRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciRiferimentoContabileInput inserisciRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciUtente")
    @ResponseWrapper(localName = "inserisciUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciUtenteOutput inserisciUtente(
        @WebParam(name = "inserisciUtenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.InserisciUtenteInput inserisciUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaCodiceVersamento")
    @ResponseWrapper(localName = "aggiornaCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaCodiceVersamentoOutput aggiornaCodiceVersamento(
        @WebParam(name = "aggiornaCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaCodiceVersamentoInput aggiornaCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTipoPagamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipoPagamento")
    @ResponseWrapper(localName = "getOpzioniTipoPagamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipoPagamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipoPagamentoOutput getOpzioniTipoPagamento(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaCduUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaCduUtente")
    @ResponseWrapper(localName = "aggiornaCduUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaCduUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaCduUtenteOutput aggiornaCduUtente(
        @WebParam(name = "aggiornaCduUtenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaCduUtenteInput aggiornaCduUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eliminaRiferimentoContabile", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaRiferimentoContabile")
    @ResponseWrapper(localName = "eliminaRiferimentoContabileResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaRiferimentoContabileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaRiferimentoContabileOutput eliminaRiferimentoContabile(
        @WebParam(name = "eliminaRiferimentoContabileInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaRiferimentoContabileInput eliminaRiferimentoContabileInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "testResources", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.TestResources")
    @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.TestResourcesResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.TestResourcesOutput testResources(
        @WebParam(name = "testResourcesInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.TestResourcesInput testResourcesInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eliminaCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaCodiceVersamento")
    @ResponseWrapper(localName = "eliminaCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaCodiceVersamentoOutput eliminaCodiceVersamento(
        @WebParam(name = "eliminaCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.EliminaCodiceVersamentoInput eliminaCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniModalitaIntegrazione", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniModalitaIntegrazione")
    @ResponseWrapper(localName = "getOpzioniModalitaIntegrazioneResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniModalitaIntegrazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniModalitaIntegrazioneOutput getOpzioniModalitaIntegrazione(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEntiAssociati", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetEntiAssociati")
    @ResponseWrapper(localName = "getEntiAssociatiResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetEntiAssociatiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetEntiAssociatiOutput getEntiAssociati(
        @WebParam(name = "getEntiAssociatiInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetEntiAssociatiInput getEntiAssociatiInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTematicaClean", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTematicaClean")
    @ResponseWrapper(localName = "getOpzioniTematicaCleanResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTematicaCleanResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTematicaCleanOutput getOpzioniTematicaClean(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniCodiceVersamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniCodiceVersamento")
    @ResponseWrapper(localName = "getOpzioniCodiceVersamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniCodiceVersamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniCodiceVersamentoOutput getOpzioniCodiceVersamento(
        @WebParam(name = "getOpzioniCodiceVersamentoInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniCodiceVersamentoInput getOpzioniCodiceVersamentoInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniMacrotipo", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniMacrotipo")
    @ResponseWrapper(localName = "getOpzioniMacrotipoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniMacrotipoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniMacrotipoOutput getOpzioniMacrotipo(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaUtente", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaUtente")
    @ResponseWrapper(localName = "aggiornaUtenteResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaUtenteResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaUtenteOutput aggiornaUtente(
        @WebParam(name = "aggiornaUtenteInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.AggiornaUtenteInput aggiornaUtenteInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOpzioniTipologiaAccertamento", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipologiaAccertamento")
    @ResponseWrapper(localName = "getOpzioniTipologiaAccertamentoResponse", targetNamespace = "http://interfacews.epaypacatalogsrv.epay.csi.it/", className = "it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipologiaAccertamentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniTipologiaAccertamentoOutput getOpzioniTipologiaAccertamento(
        @WebParam(name = "getOpzioniInput", targetNamespace = "")
        it.csi.epay.epaymodric.util.wsdl.epaypacatalogsrv.GetOpzioniInput getOpzioniInput
    ) throws Exception_Exception, EpaypacatalogsrvException_Exception, UnrecoverableException_Exception;
}
